# This is used for country/character assignments, not the one in mcmun.constants

COUNTRIES_CHARACTER = (

("Countries", (
		("Afghanistan", u"Afghanistan"), 
		("AFL-CIO, USA", u"AFL-CIO, USA"), 
		("African Development Bank ", u"African Development Bank "),
		("Albania", u"Albania"), 
		("ALECSO", u"ALECSO"), 
		("Algeria", u"Algeria"), 
		("All India Organisation of Employers", u"All India Organisation of Employers"), 
		("All-China Federation of Trade Unions", u"All-China Federation of Trade Unions"), 
		("All-Russian Confederation of Labour", u"All-Russian Confederation of Labour"), 
		("Amnesty International", u"Amnesty International"), 
		("Andorra", u"Andorra"), 
		("Angola", u"Angola"), 
		("Antigua and Barbuda", u"Antigua and Barbuda"), 
		("Argentina", u"Argentina"), 
		("Armenia", u"Armenia"), 
		("Aruba", u"Aruba"), 
		("Asia/Pacific Group On Money Laundering", u"Asia/Pacific Group On Money Laundering"),
		("Asociacion Nacional de Empresarios de Colombia", u"Asociacion Nacional de Empresarios de Colombia"), 
		("Australia", u"Australia"), 
		("Austria", u"Austria"), 
		("Azerbaijan", u"Azerbaijan"), 
		("Bahamas", u"Bahamas"), 
		("Bahrain", u"Bahrain"), 
		("Baker Hughes ", u"Baker Hughes "),
		("Bangladesh Employers' Federation", u"Bangladesh Employers' Federation"), 
		("Bangladesh Free Trade Union Congress", u"Bangladesh Free Trade Union Congress"), 
		("Bangladesh", u"Bangladesh"), 
		("Barbados", u"Barbados"), 
		("Belarus", u"Belarus"), 
		("Belgium", u"Belgium"), 
		("Belize", u"Belize"), 
		("Benin", u"Benin"), 
		("Bhutan", u"Bhutan"), 
		("Bolivia", u"Bolivia"), 
		("Bosnia and Herzegovina", u"Bosnia and Herzegovina"), 
		("Botswana Confederation of Commerce, Industry, and Manpower", u"Botswana Confederation of Commerce, Industry, and Manpower"), 
		("Botswana Federation of Trade Unions", u"Botswana Federation of Trade Unions"), 
		("Botswana", u"Botswana"), 
		("BP", u"BP"), 
		("Brazil", u"Brazil"), 
		("BRIDGE", u"BRIDGE"), 
		("Brunei", u"Brunei"), 
		("Bulgaria", u"Bulgaria"), 
		("Burkina Faso", u"Burkina Faso"), 
		("Burundi", u"Burundi"), 
		("Business Unity South Africa", u"Business Unity South Africa"), 
		("C\u00f4te d'Ivoire", u"C\u00f4te d'Ivoire"), 
		("Camara de Industrias de Guayaquil", u"Camara de Industrias de Guayaquil"), 
		("Cambodia", u"Cambodia"), 
		("Cameroon", u"Cameroon"), 
		("Canada", u"Canada"), 
		("Canadian Employers' Council", u"Canadian Employers' Council"), 
		("Canadian labour Congress", u"Canadian labour Congress"), 
		("Cape Verde", u"Cape Verde"), 
		("Caribbean Financial Action Task Force ", u"Caribbean Financial Action Task Force "),
		("CDC", u"CDC"), 
		("Central African Republic", u"Central African Republic"), 
		("Central Organisation of Free Trade Unions, Uganda (COFTU)", u"Central Organisation of Free Trade Unions, Uganda (COFTU)"), 
		("Central Organization of Trade Unions (Kenya)", u"Central Organization of Trade Unions (Kenya)"), 
		("Central Union of Workers, Colombia", u"Central Union of Workers, Colombia"), 
		("Centre of Indian Trade Unions", u"Centre of Indian Trade Unions"), 
		("Chad", u"Chad"), 
		("Chevron", u"Chevron"), 
		("Chile", u"Chile"), 
		("China Enterprise Confederation", u"China Enterprise Confederation"), 
		("China", u"China"), 
		("Chinese Taipei Federation of Industries", u"Chinese Taipei Federation of Industries"), 
		("Colombia", u"Colombia"), 
		("Comoros", u"Comoros"), 
		("Confederacao Nacional da Industria", u"Confederacao Nacional da Industria"), 
		("Confederacion de la Produccion y del Comercio", u"Confederacion de la Produccion y del Comercio"), 
		("Confederacion Patronal de la Republica Mexicana", u"Confederacion Patronal de la Republica Mexicana"), 
		("Confederation of British Industry", u"Confederation of British Industry"), 
		("Confederation of German Employers", u"Confederation of German Employers"), 
		("Confederation of Indonesia Prosperous Trade Union", u"Confederation of Indonesia Prosperous Trade Union"), 
		("Confederation of Netherlands Industry and Employers", u"Confederation of Netherlands Industry and Employers"), 
		("Confederation of Public Workers' Unions (Turkey)", u"Confederation of Public Workers' Unions (Turkey)"), 
		("Confederation of Workers of Venezuela", u"Confederation of Workers of Venezuela"), 
		("Congo", u"Congo"), 
		("Congress of South African Trade Unions", u"Congress of South African Trade Unions"), 
		("Conseil national du Patronat Burkinabe", u"Conseil national du Patronat Burkinabe"), 
		("Consejo Superior de la Empresa Privada", u"Consejo Superior de la Empresa Privada"), 
		("Consumers Health And Food Executive Agency(CHAFEA)", u"Consumers Health And Food Executive Agency(CHAFEA)"),
		("Costa Rica", u"Costa Rica"), 
		("Council of Saudi Chambers", u"Council of Saudi Chambers"), 
		("Croatia", u"Croatia"), 
		("Cuba", u"Cuba"), 
		("Curacao", u"Curacao"), 
		("Cyprus", u"Cyprus"), 
		("Czech Republic", u"Czech Republic"), 
		("Democratic People's Republic of Korea", u"Democratic People's Republic of Korea"), 
		("Democratic Republic of Congo", u"Democratic Republic of Congo"), 
		("Denmark", u"Denmark"), 
		("Dijibouti", u"Dijibouti"), 
		("Dominican Republic", u"Dominican Republic"), 
		("Ecuador Confederation of Free Trade Union Organizations", u"Ecuador Confederation of Free Trade Union Organizations"), 
		("Ecuador", u"Ecuador"), 
		("EFSA", u"EFSA"), 
		("Egypt", u"Egypt"), 
		("Egyptian Trade Union Federation", u"Egyptian Trade Union Federation"), 
		("El Salvador", u"El Salvador"), 
		("EMEA", u"EMEA"), 
		("Employers' Federation of Ceylon (Sri Lanka)", u"Employers' Federation of Ceylon (Sri Lanka)"), 
		("Employers' Federation of Pakistan", u"Employers' Federation of Pakistan"), 
		("Employers' Organizations", u"Employers' Organizations"), 
		("Enbridge", u"Enbridge"),
		("Eni ", u"Eni "),
		("ENVI", u"ENVI"), 
		("Equitorial Guinea", u"Equitorial Guinea"), 
		("Eritrea", u"Eritrea"), 
		("Estonia", u"Estonia"), 
		("Ethiopia", u"Ethiopia"), 
		("European Central Bank ", u"European Central Bank "),
		("European Commissioner For Health And Consumer Policy", u"European Commissioner For Health And Consumer Policy"),
		("European Commissioner For The Environment", u"European Commissioner For The Environment"),
		("European Medicines Agency", u"European Medicines Agency"), 
		("European Public Health Association(EUPHA)", u"European Public Health Association(EUPHA)"),
		("ExxonMobil", u"ExxonMobil"), 
		("Federacion de camaras y Asociaciones de Comercio y Produccion de Venezuela", u"Federacion de camaras y Asociaciones de Comercio y Produccion de Venezuela"), 
		("Federated States of Micronesia", u"Federated States of Micronesia"), 
		("Federation des Entreprises du Congo", u"Federation des Entreprises du Congo"), 
		("Federation Dutch Labour Movement", u"Federation Dutch Labour Movement"), 
		("Federation of American Women's Clubs Overseas", u"Federation of American Women's Clubs Overseas"), 
		("Federation of Egyptian Industries", u"Federation of Egyptian Industries"), 
		("Federation of Kenya Employers", u"Federation of Kenya Employers"), 
		("Federation of Korean Trade Unions", u"Federation of Korean Trade Unions"), 
		("Federation of Oil Unions in Iraq", u"Federation of Oil Unions in Iraq"), 
		("Federation of Trade Unions of the Republic of Kazakhstan", u"Federation of Trade Unions of the Republic of Kazakhstan"), 
		("Federation of Uganda Employers", u"Federation of Uganda Employers"), 
		("Fiji", u"Fiji"), 
		("Finland", u"Finland"), 
		("Food And Agriculture Organization(FAO)", u"Food And Agriculture Organization(FAO)"),
		("France", u"France"), 
		("French Democratic Confederation of Labour", u"French Democratic Confederation of Labour"), 
		("Gabon", u"Gabon"), 
		("Gambia", u"Gambia"), 
		("General Confederation of Peruvian Workers (CGTP)", u"General Confederation of Peruvian Workers (CGTP)"), 
		("General Federation of Jordanian Trade Unions", u"General Federation of Jordanian Trade Unions"), 
		("General Federation of Trade Unions (Syria)", u"General Federation of Trade Unions (Syria)"), 
		("General Federation of Trade Unions (UK)", u"General Federation of Trade Unions (UK)"), 
		("Georgia", u"Georgia"), 
		("German Christian Workers' Federation", u"German Christian Workers' Federation"), 
		("Germany", u"Germany"), 
		("Ghana Employers' Association", u"Ghana Employers' Association"), 
		("Ghana", u"Ghana"), 
		("Global Health Council ", u"Global Health Council "),
		("Greece", u"Greece"), 
		("Greenpeace", u"Greenpeace"), 
		("Grenada", u"Grenada"), 
		("Guam", u"Guam"), 
		("Guatemala", u"Guatemala"), 
		("Guinea - Bissau", u"Guinea - Bissau"), 
		("Guinea", u"Guinea"), 
		("Guyana", u"Guyana"), 
		("Haiti", u"Haiti"), 
		("Haliburton", u"Haliburton"),
		("Health First Europe", u"Health First Europe"),
		("Honduras", u"Honduras"), 
		("Hong Kong, China", u"Hong Kong, China"), 
		("Hungary", u"Hungary"), 
		("Husky", u"Husky"), 
		("Iberdrola", u"Iberdrola"),
		("Iceland", u"Iceland"), 
		("Imperial", u"Imperial"), 
		("India", u"India"), 
		("Indonesia", u"Indonesia"), 
		("International Federation of Red Cross and Red Crescent Societies", u"International Federation of Red Cross and Red Crescent Societies"), 
		("International Monetary Fund", u"International Monetary Fund"),
		("International Service for Human Rights", u"International Service for Human Rights"), 
		("Iran", u"Iran"), 
		("Iranian Confederation of Employers' Associations", u"Iranian Confederation of Employers' Associations"), 
		("Iraq", u"Iraq"), 
		("Ireland", u"Ireland"), 
		("Israel", u"Israel"), 
		("Italian Confederation of Workers' Trade Union", u"Italian Confederation of Workers' Trade Union"), 
		("Italy", u"Italy"), 
		("Jamaica", u"Jamaica"), 
		("Japan Business Federation", u"Japan Business Federation"), 
		("Japan", u"Japan"), 
		("Jordan", u"Jordan"), 
		("Kazakhstan", u"Kazakhstan"), 
		("Kenya", u"Kenya"), 
		("Kiribati", u"Kiribati"),
		("Kuwait", u"Kuwait"), 
		("Kyrgyzstan", u"Kyrgyzstan"), 
		("Lao People's Democratic Republic", u"Lao People's Democratic Republic"), 
		("Latvia", u"Latvia"), 
		("Lebanon", u"Lebanon"), 
		("Lesotho", u"Lesotho"), 
		("Liberia", u"Liberia"), 
		("Libya", u"Libya"), 
		("Liechtenstein", u"Liechtenstein"), 
		("Lithuania", u"Lithuania"), 
		("Luxembourg", u"Luxembourg"), 
		("Macao, China", u"Macao, China"), 
		("Madagascar", u"Madagascar"), 
		("Malawi", u"Malawi"), 
		("Malaysia", u"Malaysia"), 
		("Maldives", u"Maldives"), 
		("Mali", u"Mali"), 
		("Malta", u"Malta"), 
		("Marshall Islands", u"Marshall Islands"), 
		("Mauritania", u"Mauritania"), 
		("Mauritius", u"Mauritius"), 
		("Mexico", u"Mexico"), 
		("Middle East And North Africa Financial Action Task Force ", u"Middle East And North Africa Financial Action Task Force "),
		("Monaco", u"Monaco"), 
		("Mongolia", u"Mongolia"), 
		("Montenegro", u"Montenegro"), 
		("Morocco", u"Morocco"), 
		("Mouvement des Entreprises de France", u"Mouvement des Entreprises de France"), 
		("Mozambique", u"Mozambique"), 
		("Myanmar", u"Myanmar"), 
		("Namibia", u"Namibia"), 
		("National Confederation of Workers of Burkina", u"National Confederation of Workers of Burkina"), 
		("National Trade Unions' Federation (Libya)", u"National Trade Unions' Federation (Libya)"), 
		("National Union of Congolese Workers", u"National Union of Congolese Workers"), 
		("National Union of General Workers (Japan)", u"National Union of General Workers (Japan)"), 
		("National Union of Mine and Metal Workers of the Mexican Republic", u"National Union of Mine and Metal Workers of the Mexican Republic"), 
		("National Union of Workers (Sri Lanka)", u"National Union of Workers (Sri Lanka)"), 
		("Nauru", u"Nauru"), 
		("Nepal", u"Nepal"), 
		("Netherlands", u"Netherlands"), 
		("New Caledonia", u"New Caledonia"), 
		("New Zealand", u"New Zealand"), 
		("Nicaragua", u"Nicaragua"), 
		("Nicaraguan Workers' Centre", u"Nicaraguan Workers' Centre"), 
		("Niger", u"Niger"), 
		("Nigeria Employers' Consultative Association", u"Nigeria Employers' Consultative Association"), 
		("Nigeria", u"Nigeria"), 
		("Northern Mariana Islands", u"Northern Mariana Islands"), 
		("Norway", u"Norway"), 
		("Oman", u"Oman"), 
		("Pakistan Workers Confederation", u"Pakistan Workers Confederation"), 
		("Pakistan", u"Pakistan"), 
		("Palau", u"Palau"), 
		("Palestine", u"Palestine"), 
		("Panama", u"Panama"), 
		("Papua New Guinea", u"Papua New Guinea"), 
		("Paraguay", u"Paraguay"), 
		("Partners in Population Development", u"Partners in Population Development"), 
		("PEPFAR", u"PEPFAR"), 
		("Peru", u"Peru"), 
		("Philippines", u"Philippines"), 
		("Poland", u"Poland"), 
		("Portugal", u"Portugal"), 
		("Qatar", u"Qatar"), 
		("Republic of Korea", u"Republic of Korea"), 
		("Republic of Macedonia", u"Republic of Macedonia"), 
		("Republic of Moldova", u"Republic of Moldova"), 
		("Romania", u"Romania"), 
		("Russian Federation", u"Russian Federation"), 
		("Russian Union of Industrialists and Entrepreneurs", u"Russian Union of Industrialists and Entrepreneurs"), 
		("Rwanda", u"Rwanda"), 
		("Saint Kitts and Nevis", u"Saint Kitts and Nevis"), 
		("Saint Lucia", u"Saint Lucia"), 
		("Saint Maarten", u"Saint Maarten"), 
		("Saint Vincent and the Grenadines", u"Saint Vincent and the Grenadines"), 
		("Samoa", u"Samoa"), 
		("San Marino", u"San Marino"), 
		("Saudi Arabia", u"Saudi Arabia"), 
		("Schlumberger", u"Schlumberger"),
		("Senegal", u"Senegal"), 
		("Serbia", u"Serbia"), 
		("Seychelles", u"Seychelles"), 
		("Shell", u"Shell"), 
		("Sierra Leone Labour Congress", u"Sierra Leone Labour Congress"), 
		("Sierra Leone", u"Sierra Leone"), 
		("Singapore", u"Singapore"), 
		("Slovakia", u"Slovakia"), 
		("Slovenia", u"Slovenia"), 
		("Solomon Islands", u"Solomon Islands"), 
		("Somalia", u"Somalia"), 
		("South Africa", u"South Africa"), 
		("South Sudan", u"South Sudan"), 
		("Spain", u"Spain"), 
		("Sri Lanka", u"Sri Lanka"), 
		("Standing Committee Of European Doctors", u"Standing Committee Of European Doctors"),
		("Sudan", u"Sudan"), 
		("Surimane", u"Surimane"), 
		("Swaziland", u"Swaziland"), 
		("Sweden", u"Sweden"), 
		("Swiss Federation of Trade Unions", u"Swiss Federation of Trade Unions"), 
		("Switzerland", u"Switzerland"), 
		("Syrian Arab Republic", u"Syrian Arab Republic"), 
		("Taiwan Confederation of Trade Unions", u"Taiwan Confederation of Trade Unions"), 
		("Tajikistan", u"Tajikistan"), 
		("Talisman Energy", u"Talisman Energy"), 
		("Technip", u"Technip"),
		("Thailand", u"Thailand"), 
		("The Employers' Association of Indonesia", u"The Employers' Association of Indonesia"), 
		("The Trades Union Congress of Ghana", u"The Trades Union Congress of Ghana"), 
		("Timor-Leste", u"Timor-Leste"), 
		("Togo", u"Togo"), 
		("Tonga", u"Tonga"), 
		("Trinidad and Tobago", u"Trinidad and Tobago"), 
		("Tulavu", u"Tulavu"), 
		("Tunisia", u"Tunisia"), 
		("Turkey", u"Turkey"), 
		("Turkish Confederation of Employer Associations", u"Turkish Confederation of Employer Associations"), 
		("Turkmenistan", u"Turkmenistan"), 
		("Uganda", u"Uganda"), 
		("Ukraine", u"Ukraine"), 
		("UN Body on Petroleum", u"UN Body on Petroleum"), 
		("UNICEF", u"UNICEF"),
		("Unified Workers' Central, Brazil", u"Unified Workers' Central, Brazil"), 
		("Union of Workers in Industry, Garages, Construction Firms, Mines, and Printers (Rwanda)", u"Union of Workers in Industry, Garages, Construction Firms, Mines, and Printers (Rwanda)"), 
		("Union Patronale Suisse", u"Union Patronale Suisse"), 
		("United Arab Emirates", u"United Arab Emirates"), 
		("United Kingdom", u"United Kingdom"), 
		("United Nations Development Programme", u"United Nations Development Programme"),
		("United Republic of Tanzania", u"United Republic of Tanzania"), 
		("United States Council for International Business", u"United States Council for International Business"), 
		("United States of America", u"United States of America"), 
		("Uruguay", u"Uruguay"), 
		("Uzbekistan", u"Uzbekistan"), 
		("Vanuatu", u"Vanuatu"), 
		("Venezuela", u"Venezuela"), 
		("Viet Nam", u"Viet Nam"), 
		("VSO", u"VSO"), 
		("WHO", u"WHO"), 
		("Workers' Central Union of Cuba", u"Workers' Central Union of Cuba"), 
		("Workers' House of the Islamic Republic of Iran", u"Workers' House of the Islamic Republic of Iran"), 
		("Workers' United Centre of Chile", u"Workers' United Centre of Chile"), 
		("World Bank", u"World Bank"),
		("World Trade Organization", u"World Trade Organization"), 
		("Yemen", u"Yemen"), 
		("Zambia", u"Zambia"), 
		("Zimbabwe", u"Zimbabwe"), 
		)
),
("FIFA", (
		("\u00dcnal Aysal", u"\u00dcnal Aysal"), 
		("Alan Bowkett", u"Alan Bowkett"), 
		("Alfonso Garcia Gabarron", u"Alfonso Garcia Gabarron"), 
		("Andrea Agnelli", u"Andrea Agnelli"), 
		("Angel Maria Villar Llona", u"Angel Maria Villar Llona"), 
		("Anthony Lake", u"Anthony Lake"), 
		("Campbell Ogilvie ", u"Campbell Ogilvie "),
		("Cristiano Ronaldo - Champions League Player Representative ", u"Cristiano Ronaldo - Champions League Player Representative "),
		("Dmitry Rybolovlev", u"Dmitry Rybolovlev"), 
		("Dr. Reinhard Rauball", u"Dr. Reinhard Rauball"), 
		("Florentino P\u00e9rez", u"Florentino P\u00e9rez"), 
		("Fr\u00e9d\u00e9ric Thiriez", u"Fr\u00e9d\u00e9ric Thiriez"), 
		("Fritz Keller", u"Fritz Keller"), 
		("Gordon Taylor", u"Gordon Taylor"),
		("Hakan Jeppsson", u"Hakan Jeppsson"),
		("Hamad bin Thamer Al Thani", u"Hamad bin Thamer Al Thani"), 
		("Hans-Joachim Watzke", u"Hans-Joachim Watzke"), 
		("Henk Kivits", u"Henk Kivits"), 
		("Hennie Henrichs", u"Hennie Henrichs"), 
		("HRH Prince William, The Duke of Cambridge", u"HRH Prince William, The Duke of Cambridge"), 
		("Igor Landau", u"Igor Landau"), 
		("Javier Tebas", u"Javier Tebas"), 
		("Jean-Fran\u00e7ois van Boxmeer", u"Jean-Fran\u00e7ois van Boxmeer"), 
		("Jeremy Darroch ", u"Jeremy Darroch "),
		("Josep Maria Bartomeu", u"Josep Maria Bartomeu"), 
		("Julio Grondona", u"Julio Grondona"), 
		("Karl -Eric Nilsson", u"Karl -Eric Nilsson"),
		("Karl Hopfner", u"Karl Hopfner"), 
		("Khaldoon Al Mubarak", u"Khaldoon Al Mubarak"), 
		("Lionel Messi-FIFPro Union Representative", u"Lionel Messi-FIFPro Union Representative"),
		("Luca Campedelli", u"Luca Campedelli"), 
		("Malcom Glazer", u"Malcom Glazer"), 
		("Maurizio Beretta", u"Maurizio Beretta"), 
		("Michel Platini", u"Michel Platini"), 
		("Nasser Al-Khelaifi", u"Nasser Al-Khelaifi"), 
		("Nikolai Tolstykh", u"Nikolai Tolstykh"),
		("Phil Knight", u"Phil Knight"), 
		("Phillipe Piat ", u"Phillipe Piat "),
		("Piara Powar", u"Piara Powar"), 
		("Pierre-Marie Geronimi", u"Pierre-Marie Geronimi"), 
		("Richard N. Haythornthwaite", u"Richard N. Haythornthwaite"), 
		("Roman Abramovich", u"Roman Abramovich"), 
		("Sepp Blatter", u"Sepp Blatter"), 
		("Silvio Berlusconi", u"Silvio Berlusconi"), 
		("Sir David Richards", u"Sir David Richards"), 
		("Steve Burke", u"Steve Burke"), 
		("Wayne Rooney- PFA Players Representative ", u"Wayne Rooney- PFA Players Representative "),
		("Yildirim Demiroren ", u"Yildirim Demiroren "),
		)
),
("DEGAULLE", (
				("Andre Boulloche ", u"Andre Boulloche "),
		("Andre Malraux", u"Andre Malraux"), 
		("Bernard Cornut-Gentille", u"Bernard Cornut-Gentille"), 
		("Boegner, Jean-Marie", u"Boegner, Jean-Marie"), 
		("Buron, Robert ", u"Buron, Robert "),
		("Cabanier, Admiral Georges", u"Cabanier, Admiral Georges"), 
		("Carbonnel, Eric C.M. de", u"Carbonnel, Eric C.M. de"), 
		("Chenot, Bernard ", u"Chenot, Bernard "),
		("Couve de Murville, Maurice", u"Couve de Murville, Maurice"), 
		("de Courcel, Geoffrey Chodron", u"de Courcel, Geoffrey Chodron"), 
		("Edouard Ramonet", u"Edouard Ramonet"), 
		("Ely general paul H.R", u"Ely general paul H.R"), 
		("Emile Pelletier", u"Emile Pelletier"), 
		("Eugene Thomas ", u"Eugene Thomas "),
		("Faure, Maurice", u"Faure, Maurice"), 
		("Felix Houphouet-Boigny ", u"Felix Houphouet-Boigny "),
		("Gerrard Delavillehardier", u"Gerrard Delavillehardier"),
		("Guillamat, Pierre", u"Guillamat, Pierre"), 
		("Herve Alphand", u"Herve Alphand"), 
		("Houdet, Roger ", u"Houdet, Roger "),
		("Jacques Soustelle", u"Jacques Soustelle"), 
		("Jean Berthoin ", u"Jean Berthoin "),
		("Joxe, Louis", u"Joxe, Louis"), 
		("Laloy,Jean", u"Laloy,Jean"), 
		("Louis Jacquinot ", u"Louis Jacquinot "),
		("Lucet, Charles", u"Lucet, Charles"), 
		("Martin, General Andre", u"Martin, General Andre"), 
		("Max Lejeune", u"Max Lejeune"), 
		("Michel Debre", u"Michel Debre"), 
		("Michel Hardodier", u"Michel Hardodier"),
		("Michelet, Edmond ", u"Michelet, Edmond "),
		("Mollet, Guy", u"Mollet, Guy"), 
		("Paul Bacon", u"Paul Bacon"), 
		("Pflimlin, Pierre", u"Pflimlin, Pierre"), 
		("Pierre Lamare", u"Pierre Lamare"),
		("Pinay, Antoine", u"Pinay, Antoine"), 
		("Pineau, Christian", u"Pineau, Christian"), 
		("Sudreau, Pierre", u"Sudreau, Pierre"),
		("valery, Francois", u"valery, Francois"), 
		("Wormser, Olivier", u"Wormser, Olivier"), 
		)
),
("IRAN", (
		("Alan Fiers", u"Alan Fiers"),
		("Anne Armstrong", u"Anne Armstrong"), 
		("Caspar Weinberger", u"Caspar Weinberger"), 
		("Claire George", u"Claire George"),
		("Donald Regan", u"Donald Regan"), 
		("Duanne Claridge", u"Duanne Claridge"),
		("Edwin Meese III", u"Edwin Meese III"), 
		("Elliot Abrams", u"Elliot Abrams"), 
		("General Richard Secord", u"General Richard Secord"), 
		("George H.W. Bush", u"George H.W. Bush"), 
		("George Schultz", u"George Schultz"), 
		("James Brady", u"James Brady"), 
		("John Poindexter", u"John Poindexter"), 
		("Michael Ledeen", u"Michael Ledeen"), 
		("Oliver North", u"Oliver North"), 
		("Pat Buchanan ", u"Pat Buchanan "),
		("Richard Brenneke", u"Richard Brenneke"), 
		("Robert McFarlane ", u"Robert McFarlane "),
		("Thomas Clines", u"Thomas Clines"), 
		("William Casey", u"William Casey"), 
		)
),
("CAP", (
		("Andrew Delisle", u"Andrew Delisle"), 
		("Bertha Allen", u"Bertha Allen"), 
		("D'Arcy McNickle", u"D'Arcy McNickle"), 
		("David Ahenakew", u"David Ahenakew"), 
		("Elizabeth Isbister", u"Elizabeth Isbister"), 
		("Elsie Knott", u"Elsie Knott"), 
		("Eva Rickard", u"Eva Rickard"), 
		("George Manuel", u"George Manuel"), 
		("Harold Cardinal", u"Harold Cardinal"), 
		("John Turner", u"John Turner"), 
		("Judd Buchanan", u"Judd Buchanan"), 
		("Louis Karonaiktajeh Hall", u"Louis Karonaiktajeh Hall"), 
		("Mary Two-Axe Earley", u"Mary Two-Axe Earley"), 
		("Maxim Gros-Louis", u"Maxim Gros-Louis"), 
		("Morris Thompson", u"Morris Thompson"), 
		("Noel Doucette", u"Noel Doucette"), 
		("Oodgeroo Noonuccal", u"Oodgeroo Noonuccal"), 
		("Robert Bourassa", u"Robert Bourassa"), 
		("Tagek Curley", u"Tagek Curley"), 
		("Walter Deiter", u"Walter Deiter"), 
		)
),
("BNW", (
		("Arch-Community-songster", u"Arch-Community-songster"), 
		("Chancellor of Ford University", u"Chancellor of Ford University"), 
		("Commissioner of Eurasian Police Force", u"Commissioner of Eurasian Police Force"), 
		("Deputy Director of the Hatchery and Conditioning Centre, Conditioning Division", u"Deputy Director of the Hatchery and Conditioning Centre, Conditioning Division"), 
		("Director of Hatcheries and Conditioning", u"Director of Hatcheries and Conditioning"), 
		("Director of Health and Wellness Service", u"Director of Health and Wellness Service"), 
		("Director of the Central Eurasia Bank", u"Director of the Central Eurasia Bank"), 
		("Director of the Department of agriculture and mining", u"Director of the Department of agriculture and mining"), 
		("Director of the Eurasia Media Centre", u"Director of the Eurasia Media Centre"), 
		("Minister of Foreign Affairs", u"Minister of Foreign Affairs"), 
		("Minister of defense", u"Minister of defense"), 
		("Warden of the Savage Reservation", u"Warden of the Savage Reservation"), 
		)
),
("AMAZON", (
		("Alain Monie", u"Alain Monie"), 
		("Andrew R. Jassy", u"Andrew R. Jassy"), 
		("David A. Zapolsky", u"David A. Zapolsky"), 
		("Diego Piacentini", u"Diego Piacentini"), 
		("Dr. Werner Vogels", u"Dr. Werner Vogels"), 
		("Emmeet Shear", u"Emmeet Shear"),
		("James S. Gorelick", u"James S. Gorelick"), 
		("Jeffrey A. Wilke", u"Jeffrey A. Wilke"), 
		("Jeffrey M. Blackburn", u"Jeffrey M. Blackburn"), 
		("Jeffrey P. Bezos", u"Jeffrey P. Bezos"), 
		("John Seely Brown", u"John Seely Brown"), 
		("Johnathan J. Rubinstein", u"Johnathan J. Rubinstein"), 
		("L. John Doerr", u"L. John Doerr"),
		("Mark Onetto ", u"Mark Onetto "),
		("Michael Frazzini", u"Michael Frazzini"),
		("Michelle L. Wilson ", u"Michelle L. Wilson "),
		("Myrtle S. Potter", u"Myrtle S. Potter"),
		("Neil Lindsay", u"Neil Lindsay"),
		("Patricia Q. Stonesifer", u"Patricia Q. Stonesifer"), 
		("Sebastian J. Gunningham", u"Sebastian J. Gunningham"), 
		("Shelley L. Reynolds", u"Shelley L. Reynolds"), 
		("Steven Kessel", u"Steven Kessel"), 
		("Thomas J. Szkutak", u"Thomas J. Szkutak"), 
		("Thomas O. Ryder", u"Thomas O. Ryder"), 
		("Tom A. Alberg", u"Tom A. Alberg"), 
		("William B. (Bing) Gordon", u"William B. (Bing) Gordon"), 
		)
),
("Orange 1", (
		("CEO of Ukrinform - state-run news agency", u"CEO of Ukrinform - state-run news agency"), 
		("Chief of General Staff - Sergiy Kirichenko", u"Chief of General Staff - Sergiy Kirichenko"), 
		("Foreign Intelligence Service of Ukraine - Oleh HryhorovychSyniansy", u"Foreign Intelligence Service of Ukraine - Oleh HryhorovychSyniansy"), 
		("Gennadiy Bogolyubov", u"Gennadiy Bogolyubov"), 
		("Military Advisor - Igor Nirieych", u"Military Advisor - Igor Nirieych"), 
		("Military Advisor - Oleksandr Zatynayko", u"Military Advisor - Oleksandr Zatynayko"), 
		("Minister of Defence - Anatoliy Hrytsenko", u"Minister of Defence - Anatoliy Hrytsenko"), 
		("Minister of Economy - Arseniy Yatsenyuk", u"Minister of Economy - Arseniy Yatsenyuk"), 
		("Minister of European Integration - Hukejk Ravigja", u"Minister of European Integration - Hukejk Ravigja"), 
		("Minister of Foreign Affairs - Nasemu Ujisycka", u"Minister of Foreign Affairs - Nasemu Ujisycka"), 
		("Minister of Internal Affairs - Yuriy Vitaliyovych Lutsenko", u"Minister of Internal Affairs - Yuriy Vitaliyovych Lutsenko"), 
		("Minister of Justice - Yuriy Yekhanurov", u"Minister of Justice - Yuriy Yekhanurov"), 
		("Minister of Social Policy - Vyacheslav Kyrylenko", u"Minister of Social Policy - Vyacheslav Kyrylenko"), 
		("Prime Minister - Yulia Tymoshenko", u"Prime Minister - Yulia Tymoshenko"), 
		)
),
("Orange 2", (
		("Anatoliy Zlenko - Foreign Affairs", u"Anatoliy Zlenko - Foreign Affairs"), 
		("General Yuri Oriov - Military Advisor (Russian)", u"General Yuri Oriov - Military Advisor (Russian)"),
		("General Vitali Govrachych - Military Advisor (Ukrainian)", u"General Vitali Govrachych - Military Advisor (Ukrainian)"), 
		("General Volodymyr Shkidchenko - Defence", u"General Volodymyr Shkidchenko - Defence"), 
		("Sergei Lebedev - Military Advisor (Russian)", u"Sergei Lebedev - Military Advisor (Russian)"), 
		("Ivan Kyrylenko - Deputy Prime Minister", u"Ivan Kyrylenko - Deputy Prime Minister"), 
		("Mykola Azarov - Chairman of the Party", u"Mykola Azarov - Chairman of the Party"), 
		("Olehsandr Lavrynobych - Justice", u"Olehsandr Lavrynobych - Justice"), 
		("Oleksandr Yefremov - Deputy Chairman of the Party of Regions on Relations with the Parliament of Ukraine. (DCPRRPU)", u"Oleksandr Yefremov - Deputy Chairman of the Party of Regions on Relations with the Parliament of Ukraine. (DCPRRPU)"), 
		("Runit Akhmetov Ukrainian Billionaire", u"Runit Akhmetov Ukrainian Billionaire"), 
		("Sergey Kurchenko - Gas King Media Mogul (Ukrainian) - Long Term Backer of Yanukovitch", u"Sergey Kurchenko - Gas King Media Mogul (Ukrainian) - Long Term Backer of Yanukovitch"), 
		("Vadim Novinsky - Ukrainian Business Man", u"Vadim Novinsky - Ukrainian Business Man"), 
		("Valery Khoroshkovsky - Economy and European Integrations", u"Valery Khoroshkovsky - Economy and European Integrations"), 
		("Yevhen Petrovych - Political Advisor to Yanikovitch", u"Yevhen Petrovych - Political Advisor to Yanikovitch"), 
		("Yury Smimov - Interior Affairs", u"Yury Smimov - Interior Affairs"),
		("Vasyl Dzharty - Interior Affairs", u"Vasyl Dzharty - Interior Affairs"), 
		)
),
("RFE", (
		("Abdulrachmann (Abo) Fatalibey", u"Abdulrachmann (Abo) Fatalibey"), 
		("Admiral Harold B. Miller", u"Admiral Harold B. Miller"), 
		("Arthur W. Page", u"Arthur W. Page"), 
		("Bernard Yarrow", u"Bernard Yarrow"), 
		("Blagoy Dimov", u"Blagoy Dimov"), 
		("Cord Meyer", u"Cord Meyer"), 
		("Dragos Ungur", u"Dragos Ungur"), 
		("Emil Csonka", u"Emil Csonka"), 
		("Ferdinand Peroutka", u"Ferdinand Peroutka"), 
		("Frank Altschul", u"Frank Altschul"), 
		("Geza Ekecs ", u"Geza Ekecs "),
		("Gyula Borbandi", u"Gyula Borbandi"), 
		("Gyula Dessewffy", u"Gyula Dessewffy"), 
		("Henry Ford II", u"Henry Ford II"), 
		("Herbert Gross", u"Herbert Gross"), 
		("Istvan Deak", u"Istvan Deak"), 
		("Jan Nowak-Jezioranski", u"Jan Nowak-Jezioranski"), 
		("Jaroslav Jan Endrst", u"Jaroslav Jan Endrst"), 
		("Julius Firt", u"Julius Firt"), 
		("Kiril Vanchev ", u"Kiril Vanchev "),
		("Konrad Kellen", u"Konrad Kellen"), 
		("Noel Bernard ", u"Noel Bernard "),
		("Oskar R. lange", u"Oskar R. lange"), 
		("Paul Henze", u"Paul Henze"), 
		("Pavel Tigrid", u"Pavel Tigrid"), 
		("Ralph E. Walter", u"Ralph E. Walter"), 
		("Richard Condon", u"Richard Condon"), 
		("Robert E. Lang", u"Robert E. Lang"), 
		("Rustam Ayanov(Kazakh Division)", u"Rustam Ayanov(Kazakh Division)"), 
		("Samuel S. Walker", u"Samuel S. Walker"),
		("Whitney Shepardson", u"Whitney Shepardson"), 
		("Wiktor Troscianko", u"Wiktor Troscianko"), 
		("Wilbur Schramm", u"Wilbur Schramm"),
		("Willam E. Griffith", u"Willam E. Griffith"), 
		("Zbigniew Brzezinski", u"Zbigniew Brzezinski"), 
		("Zoltan Szabo", u"Zoltan Szabo"), 
		)
),
("IRAQ", (
		("Andrew Card", u"Andrew Card"), 
		("Colin Powell", u"Colin Powell"), 
		("Condolezza Rice", u"Condolezza Rice"), 
		("Donald Evans - Secretary Of Commerce", u"Donald Evans - Secretary Of Commerce"),
		("Donald Rumsfeld", u"Donald Rumsfeld"), 
		("Gale Norton - Secretary Of The Interior", u"Gale Norton - Secretary Of The Interior"),
		("George Tenet", u"George Tenet"), 
		("George W. Casey, Jr. - Vice Chief Of Staff Of The Army", u"George W. Casey, Jr. - Vice Chief Of Staff Of The Army"),
		("Gregory Mankiw - Chairman Of The Council Of Economic Advisors", u"Gregory Mankiw - Chairman Of The Council Of Economic Advisors"),
		("John Ashcroft", u"John Ashcroft"), 
		("John Negroponte", u"John Negroponte"), 
		("John Snow", u"John Snow"), 
		("Michael Moseley", u"Michael Moseley"), 
		("Paul Bremer", u"Paul Bremer"), 
		("Ricardo Sanchez", u"Ricardo Sanchez"), 
		("Richard Myers", u"Richard Myers"), 
		("Robert Mueller - Director Of The FBI", u"Robert Mueller - Director Of The FBI"),
		("Spencer Abraham", u"Spencer Abraham"), 
		("Tom Ridge", u"Tom Ridge"), 
		("Tommy Franks", u"Tommy Franks"), 
		)
),
("1984", (
		("Director of Reform", u"Director of Reform"), 
		("Minister of Love", u"Minister of Love"), 
		("Minister of Peace", u"Minister of Peace"), 
		("Minister of Plenty", u"Minister of Plenty"), 
		("Minister of Truth", u"Minister of Truth"), 
		("President of Proletariat", u"President of Proletariat"), 
		("Proletariat Administrator", u"Proletariat Administrator"), 
		("Secretary of Armed Forces", u"Secretary of Armed Forces"), 
		("Secretary of Culture", u"Secretary of Culture"), 
		("Secretary of Economy", u"Secretary of Economy"), 
		("Secretary of Education", u"Secretary of Education"), 
		("Secretary of Foreign Intelligence", u"Secretary of Foreign Intelligence"), 
		)
),
("AD HOC", (
		("Confidential #1", u"Confidential #1"), 
		("Confidential #2", u"Confidential #2"), 
		("Confidential #3", u"Confidential #3"), 
		("Confidential #4", u"Confidential #4"), 
		("Confidential #5", u"Confidential #5"), 
		("Confidential #6", u"Confidential #6"), 
		("Confidential #7", u"Confidential #7"), 
		("Confidential #8", u"Confidential #8"), 
		("Confidential #9", u"Confidential #9"),	
		("Confidential #10", u"Confidential #10"), 
		("Confidential #11", u"Confidential #11"), 
		("Confidential #12", u"Confidential #12"), 
		("Confidential #13", u"Confidential #13"), 
		("Confidential #14", u"Confidential #14"), 
		("Confidential #15", u"Confidential #15"),
		)
),
("UNSC", (
		("Armenia", u"Armenia"), 
		("Belgium", u"Belgium"), 
		("Brazil", u"Brazil"), 
		("Canada", u"Canada"), 
		("China", u"China"), 
		("Ethiopia", u"Ethiopia"), 
		("France", u"France"), 
		("Morocco", u"Morocco"), 
		("Pakistan", u"Pakistan"), 
		("Russia", u"Russia"), 
		("Saudi Arabia", u"Saudi Arabia"), 
		("USA", u"USA"), 
		("Uganda", u"Uganda"), 
		("United Kingdom", u"United Kingdom"), 
		("Venezuela", u"Venezuela"), 
		)
),
("Mughal", (
		("Darogha-I Dak Wa Sawanih (Chief of Intelligence and Police)", u"Darogha-I Dak Wa Sawanih (Chief of Intelligence and Police)"), 
		("Duke of Goa", u"Duke of Goa"), 
		("Emissary of House Dinajara", u"Emissary of House Dinajara"), 
		("Lord of Rajasthan", u"Lord of Rajasthan"), 
		("Marathan Ambassador", u"Marathan Ambassador"), 
		("Mir Bakhshi (Minister of War)", u"Mir Bakhshi (Minister of War)"), 
		("Muhtasib (Officer of Religious Morals)", u"Muhtasib (Officer of Religious Morals)"), 
		("Sadr(Chief Justice)", u"Sadr(Chief Justice)"), 
		("Sipah Salar (Governor) Of Bengal", u"Sipah Salar (Governor) Of Bengal"),
		("Sipah Salar (Governor) Of Bihar", u"Sipah Salar (Governor) Of Bihar"),
		("Sipah Salar (Governor) Of Delhi", u"Sipah Salar (Governor) Of Delhi"),
		("Sipah Salar (Governor) Of Kabul", u"Sipah Salar (Governor) Of Kabul"),
		("Sipah Salar (Governor) Of Lahore", u"Sipah Salar (Governor) Of Lahore"),
		("Sipah Salar(Governor of Bijapur)", u"Sipah Salar(Governor of Bijapur)"), 
		("Sipah Salar(Governor of Gujarat)", u"Sipah Salar(Governor of Gujarat)"), 
		("Sipah Salar(Governor of Hyderabad)", u"Sipah Salar(Governor of Hyderabad)"), 
		("Sipah Salar(Governor of Punjab)", u"Sipah Salar(Governor of Punjab)"), 
		("Sipah Salar(Governor of Rajput)", u"Sipah Salar(Governor of Rajput)"), 
		("Vizier (Minister of Finance)", u"Vizier (Minister of Finance)"), 
		("Vizier (Minister of Foreign Affairs)", u"Vizier (Minister of Foreign Affairs)"), 		)
),
)

ASSIGN_TYPE = (( True, 'Country'), (False, 'Character'))

COUNTRYLIST = [
	"Afghanistan",
	"Albania",
	"Algeria",
	"Andorra",
	"Angola",
	"Antigua and Barbuda",
	"Argentina",
	"Armenia",
	"Australia",
	"Austria",
	"Azerbaijan",
	"Bahamas",
	"Bahrain",
	"Bangladesh",
	"Barbados",
	"Belarus",
	"Belgium",
	"Belize",
	"Benin",
	"Bhutan",
	"Bolivia",
	"Bosnia and Herzegovina",
	"Botswana",
	"Brazil",
	"Brunei",
	"Bulgaria",
	"Burkina Faso",
	"Burundi",
	"Cambodia",
	"Cameroon",
	"Canada",
	"Cape Verde",
	"Central African Republic",
	"Chad",
	"Chile",
	"China",
	"Colombia",
	"Comoros",
	"Congo",
	"Costa Rica",
	"Cote d'Ivoire",
	"Croatia",
	"Cuba",
	"Cyprus",
	"Czech Republic",
	"Democratic People's Republic of Korea",
	"Democratic Republic of Congo",
	"Denmark",
	"Dijibouti",
	"Dominican Republic",
	"Ecuador",
	"Egypt",
	"El Salvador",
	"Equitorial Guinea",
	"Eritrea",
	"Estonia",
	"Ethiopia",
	"Fiji",
	"Finland",
	"France",
	"Gabon",
	"Gambia",
	"Georgia",
	"Germany",
	"Ghana",
	"Greece",
	"Grenada",
	"Guatemala",
	"Guinea",
	"Guinea - Bissau",
	"Guyana",
	"Haiti",
	"Honduras",
	"Hungary",
	"Iceland",
	"India",
	"Indonesia",
	"Iran",
	"Iraq",
	"Ireland",
	"Israel",
	"Italy",
	"Jamaica",
	"Japan",
	"Jordan",
	"Kazakhstan",
	"Kenya",
	"Kuwait",
	"Kyrgyzstan",
	"Lao People's Democratic Republic",
	"Latvia",
	"Lebanon",
	"Lesotho",
	"Liberia",
	"Libya",
	"Liechtenstein",
	"Lithuania",
	"Luxembourg",
	"Madagascar",
	"Malawi",
	"Malaysia",
	"Maldives",
	"Mali",
	"Malta",
	"Marshall Islands",
	"Mauritania",
	"Mauritius",
	"Mexico",
	"Federated States of Micronesia",
	"Monaco",
	"Mongolia",
	"Montenegro",
	"Morocco",
	"Mozambique",
	"Myanmar",
	"Namibia",
	"Nauru",
	"Nepal",
	"Netherlands",
	"New Zealand",
	"Nicaragua",
	"Niger",
	"Nigeria",
	"Norway",
	"Oman",
	"Pakistan",
	"Palau",
	"Panama",
	"Papa New Guinea",
	"Paraguay",
	"Peru",
	"Philippines",
	"Poland",
	"Portugal",
	"Qatar",
	"Republic of Korea",
	"Republic of Moldova",
	"Romania",
	"Russian Federation",
	"Rwanda",
	"Saint Kitts and Nevis",
	"Saint Lucia",
	"Saint Vincent and the Grenadines",
	"Samoa",
	"San Marino",
	"Saudi Arabia",
	"Senegal",
	"Serbia",
	"Seychelles",
	"Sierra Leone",
	"Singapore",
	"Slovakia",
	"Slovenia",
	"Solomon Islands",
	"Somalia",
	"South Africa",
	"South Sudan",
	"Spain",
	"Sri Lanka",
	"Sudan",
	"Surimane",
	"Swaziland",
	"Sweden",
	"Switzerland",
	"Syrian Arab Republic",
	"Tajikistan",
	"Thailand",
	"Republic of Macedonia",
	"Timor-Leste",
	"Togo",
	"Tonga",
	"Trinidad and Tobago",
	"Tunisia",
	"Turkey",
	"Turkmenistan",
	"Tulavu",
	"Uganda",
	"Ukraine",
	"United Arab Emirates",
	"United Kingdom",
	"United Republic of Tanzania",
	"United States of America",
	"Uruguay",
	"Uzbekistan",
	"Vanuatu",
	"Venezuela",
	"Viet Nam",
	"Yemen",
	"Zambia",
	"Zimbabwe",	
]

