# This is used for country/character assignments, not the one in mcmun.constants

COUNTRIES_CHARACTER = (
    ('Countries', (
       ('AF', u'Afghanistan'), ('AL', u'Albania'), ('AC', u'ALECSO'),('DZ', u'Algeria'), 
	('AD', u'Andorra'), ('AO', u'Angola'), 
	('AG', u'Antigua and Barbuda'), ('AR', u'Argentina'), ('AM', u'Armenia'), 
	('AU', u'Australia'), 
	('AT', u'Austria'), ('AZ', u'Azerbaijan'), ('BS', u'Bahamas'), 
	('BH', u'Bahrain'), ('BD', u'Bangladesh'), ('BB', u'Barbados'), 
	('BY', u'Belarus'), ('BE', u'Belgium'), ('BZ', u'Belize'), 
	('BJ', u'Benin'), ('BT', u'Bhutan'), 
	('BO', u'Bolivia, Plurinational State of'), 
	('BA', u'Bosnia and Herzegovina'), ('BW', u'Botswana'), 
	('BR', u'Brazil'), ('BN', u'Brunei Darussalam'), ('BG', u'Bulgaria'), 
	('BF', u'Burkina Faso'), ('BI', u'Burundi'), ('KH', u'Cambodia'), 
	('CM', u'Cameroon'), ('CA', u'Canada'), ('CV', u'Cape Verde'), 
	('TD', u'Chad'), 
	('CL', u'Chile'), ('CN', u'China'), ('CO', u'Colombia'), ('KM', u'Comoros'), 
	('CG', u'Congo'), ('CR', u'Costa Rica'), ('CI', u"C\xf4te D'ivoire"), ('HR', u'Croatia'), 
	('CU', u'Cuba'), ('CY', u'Cyprus'), 
	('CZ', u'Czech Republic'), ('KP', u"Democratic People's Republic of Korea"),
	('RC', u'Democratic Republic of Congo'), ('DK', u'Denmark'), 
	('DJ', u'Djibouti'), ('DO', u'Dominican Republic'), 
	('EC', u'Ecuador'), ('EG', u'Egypt'), ('SV', u'El Salvador'), 
	('GQ', u'Equatorial Guinea'), ('ER', u'Eritrea'),
	('ET', u'Ethiopia'), ('FJ', u'Fiji'), ('FI', u'Finland'), 
	('FR', u'France'), ('GA', u'Gabon'), ('GM', u'Gambia'), 
	('GE', u'Georgia'), ('DE', u'Germany'), ('GH', u'Ghana'), 
	('GR', u'Greece'), ('GD', u'Grenada'), ('GT', u'Guatemala'), 
	('GN', u'Guinea'), ('GY', u'Guyana'), ('HT', u'Haiti'), 
	('HN', u'Honduras'), ('HU', u'Hungary'), 
	('IS', u'Iceland'), ('IN', u'India'), ('ID', u'Indonesia'),
	('IM', u'International Organization for Migration'),
	('IR', u'Iran, Islamic Republic of'), ('IQ', u'Iraq'), ('IE', u'Ireland'), 
	('IL', u'Israel'), ('IT', u'Italy'), ('JM', u'Jamaica'), ('JP', u'Japan'), 
	('JO', u'Jordan'), ('KZ', u'Kazakhstan'), ('KE', u'Kenya'), 
	('KW', u'Kuwait'), ('KG', u'Kyrgyzstan'), 
	('LA', u"Lao People's Democratic Republic"), ('LB', u'Lebanon'), 
	('LS', u'Lesotho'), ('LR', u'Liberia'), ('LY', u'Libya'), 
	('LT', u'Lithuania'), ('LU', u'Luxembourg'), 
	('MG', u'Madagascar'), 
	('MW', u'Malawi'), ('MY', u'Malaysia'), ('MV', u'Maldives'), 
	('ML', u'Mali'), ('MT', u'Malta'), ('MR', u'Mauritania'), 
	('MU', u'Mauritius'), ('MX', u'Mexico'), ('MC', u'Monaco'), 
	('MN', u'Mongolia'), ('MA', u'Morocco'), ('MZ', u'Mozambique'), 
	('MM', u'Myanmar'), ('NA', u'Namibia'),
	('NP', u'Nepal'), ('NL', u'Netherlands'),
	('NZ', u'New Zealand'), ('NI', u'Nicaragua'), ('NE', u'Niger'), 
	('NG', u'Nigeria'), ('NO', u'Norway'), 
	('OM', u'Oman'), ('IC', u'Organization of the Islamic Cooperation'), ('PK', u'Pakistan'), 
	('PS', u'Palestine'), ('PA', u'Panama'), 
	('PG', u'Papua New Guinea'), ('PY', u'Paraguay'), ('PE', u'Peru'), ('PH', u'Philippines'), 
	('PL', u'Poland'), ('PT', u'Portugal'), ('QA', u'Qatar'), 
	('KR', u'Republic of Korea'), ('MD', u'Republic of Macedonia'), 
	('RO', u'Romania'), ('RU', u'Russian Federation'), 
	('RW', u'Rwanda'), ('SR', u'Sahrawi Republic'), 
	('KN', u'Saint Kitts and Nevis'), ('LC', u'Saint Lucia'), 
	('VC', u'Saint Vincent and the Grenadines'), ('ST', u'Sao Tome and Principe'), 
	('SA', u'Saudi Arabia'), ('SN', u'Senegal'), 
	('RS', u'Serbia'), ('SC', u'Seychelles'), ('SL', u'Sierra Leone'), 
	('SG', u'Singapore'), ('SK', u'Slovakia'), ('SO', u'Somalia'), ('ZA', u'South Africa'), 
	('SS', u'South Sudan'), 
	('ES', u'Spain'), ('LK', u'Sri Lanka'), ('SD', u'Sudan'), ('SR', u'Suriname'), 
	('SZ', u'Swaziland'), ('SE', u'Sweden'), 
	('CH', u'Switzerland'), ('SY', u'Syrian Arab Republic'), ('TH', u'Thailand'), 
	('TL', u'Timor-leste'), ('TG', u'Togo'), 
	('TT', u'Trinidad and Tobago'), 
	('TN', u'Tunisia'), ('TR', u'Turkey'), ('TM', u'Turkmenistan'), 
	('UG', u'Uganda'), ('UA', u'Ukraine'), ('UN', u'UNHCR'), ('AE', u'United Arab Emirates'), 
	('GB', u'United Kingdom'), ('TZ', u'United Republic of Tanzania'), 
	('US', u'United States of America'), ('UY', u'Uruguay'), ('UZ', u'Uzbekistan'), 
	('VU', u'Vanuatu'), 
	('VE', u'Venezuela, Bolivarian Republic of'), ('VN', u'Viet Nam'), 
	('YE', u'Yemen'), 
	('ZM', u'Zambia'), ('ZW', u'Zimbabwe'),
        )
    ),
    ('IGF', (
        ('Mr. Abdelaziz Hilali', u'Mr. Abdelaziz Hilali'),
		('Mr. Charles Sha ban', u'Mr. Charles Sha ban'),
		('Mr. Chris Disspain', u'Mr. Chris Disspain'),
		('Mr. Chunlu Zhao', u'Mr. Chunlu Zhao'),
		('Mr. Esmat Baher', u'Mr. Esmat Baher'),
		('Mr. Felix Samakande', u'Mr. Felix Samakande'),
		('Mr. Igor Khimchenko', u'Mr. Igor Khimchenko'),
		('Mr. Igor Ostrowski', u'Mr. Igor Ostrowski'),
		('Mr. Izumi Aizu', u'Mr. Izumi Aizu'),
		('Mr. Jean Paul Philippot', u'Mr. Jean Paul Philippot'),
		('Mr. Jeff Brueggeman', u'Mr. Jeff Brueggeman'),
		('Mr. Jimson Olufuye', u'Mr. Jimson Olufuye'),
		('Mr. Liang Guo', u'Mr. Liang Guo'),
		('Mr. Manuel Dengo', u'Mr. Manuel Dengo'),
		('Mr. Mark Carvell', u'Mr. Mark Carvell'),
		('Mr. Masanobu Katoh', u'Mr. Masanobu Katoh'),
		('Mr. Ondrej Filip', u'Mr. Ondrej Filip'),
		('Mr. Paul Rendrek', u'Mr. Paul Rendrek'),
		('Mr. Paul Wilson', u'Mr. Paul Wilson'),
		('Mr. Peter Major', u'Mr. Peter Major'),
		('Mr. Raul Echeberria', u'Mr. Raul Echeberria'),
		('Mr. Reshan Dewapura', u'Mr. Reshan Dewapura'),
		('Mr. Ricardo Pedraza Barrios', u'Mr. Ricardo Pedraza Barrios'),
		('Mr. Sardjoeni Moedjiono', u'Mr. Sardjoeni Moedjiono'),
		('Mr. Tero Mustala', u'Mr. Tero Mustala'),
		('Mr. Thomas Spiller', u'Mr. Thomas Spiller'),
		('Mr. Vladimir Radunovic', u'Mr. Vladimir Radunovic'),
		('Mr. William Drake', u'Mr. William Drake'),
		('Mr. Zahid U. Jamil', u'Mr. Zahid U. Jamil'),
		('Ms. Ana Christina Neves Amoroso', u'Ms. Ana Christina Neves Amoroso'),
		('Ms. Anju Mangal', u'Ms. Anju Mangal'),
		('Ms. Anriette Esterhuysen', u'Ms. Anriette Esterhuysen'),
		('Ms. Ayesha Hassan', u'Ms. Ayesha Hassan'),
		('Ms. Carolina Aguerre', u'Ms. Carolina Aguerre'),
		('Ms. Constance Bommelaer', u'Ms. Constance Bommelaer'),
		('Ms. Graciela Selaimen', u'Ms. Graciela Selaimen'),
		('Ms. Heather Dryden', u'Ms. Heather Dryden'),
		('Ms. Jennifer A. Warren', u'Ms. Jennifer A. Warren'),
		('Ms. Judith Okite', u'Ms. Judith Okite'),
		('Ms. Lillian Nalwoga', u'Ms. Lillian Nalwoga'),
		('Ms. Lucinda Fell', u'Ms. Lucinda Fell'),
		('Ms. Mervi Kultamaa', u'Ms. Mervi Kultamaa'),
		('Ms. Nurani Nimpuno', u'Ms. Nurani Nimpuno'),
		('Ms. Olga del Carmen Cavalli', u'Ms. Olga del Carmen Cavalli'),
		('Ms. Sanja Kelly', u'Ms. Sanja Kelly'),
		('Ms. Theresa Swineheart', u'Ms. Theresa Swineheart'),
		('Ms. Valeria Betancourt', u'Ms. Valeria Betancourt'),
		('Ms. Veronica Cretu', u'Ms. Veronica Cretu'),
		('Ms. Wendy Seltzer', u'Ms. Wendy Seltzer'),
		('Ms. Yuliya Morenets', u'Ms. Yuliya Morenets'),
		)
	),
	('Meeting of the Emirs', (
		('Bahrain', u'Hakim Sheikh Isa ibn Salman Al Khalifa (Bahrain)'),
		('Abu Dhabi', u'Emir Sheikh Zayed bin Sultan Al Nahyan (Abu Dhabi)'),
		('Ras Al Khamiah', u'Emir Sheikh Saqr bin Mohammad al-Qassimi (Ras Al Khamiah)'),
		('Ajman', u'Emir Sheikh Rashid ibn Humayd Al Nuaimi (Ajman)'),
		('Dubai', u'Emir Sheikh Rashid bin Saeed Al Maktoum (Dubai)'),
		('Al Fujairah', u'Emir Sheikh Mohammed bin Hamad (Al Fujairah)'),
		('Sharjah', u'Emir Sheikh Khalid III bin Muhammad Al Qasimi (Sharjah)'),
		('Umm Al Qawain', u'Emir Sheikh Ahmad bin Rashid Al Mu\'alla (Umm Al Qawain)'),
		('Qatar', u'Emir Sheikh Ahmad bin Ali Al Thani (Qatar)'),
        	)
    	),
	('European Public Health Alliance', (
		('ACTIS-Norwegian Policy Network on Alcohol and Drugs', u'ACTIS-Norwegian Policy Network on Alcohol and Drugs'),
		('AGE Platform Europe', u'AGE Platform Europe'),
                ('Alcohol Action Ireland', u'Alcohol Action Ireland'),
                ('Alcohol Focus Scotland', u'Alcohol Focus Scotland'),
                ('Armenian Public Health Union', u'Armenian Public Health Union'),
                ('Association for Natural Medicine in Europe', u'Association for Natural Medicine in Europe'),
                ('Association Nationale de Prevention en Alcoologie et Addictologie (ANPAA)', u'Association Nationale de Prevention en Alcoologie et Addictologie (ANPAA)'),
                ('Association Net+/Udruga Pet+', u'Association Net+/Udruga Pet+'),
                ('Association of European Cancer Leagues (ECL)', u'Association of European Cancer Leagues (ECL)'),
                ('Baltic Region Healthy Cities Association - WHO Collaborating Centre for Healthy Cities and Urban Health in Baltic Region', u'Baltic Region Healthy Cities Association - WHO Collaborating Centre for Healthy Cities and Urban Health in Baltic Region'),
                ('British Heart Foundation Health Promotion Research Group (BHF HPRG)', u'British Heart Foundation Health Promotion Research Group (BHF HPRG)'),
                ('Bulgarian Association for Patients\' Rights Defence', u'Bulgarian Association for Patients\' Rights Defence'),
                ('Cancer Research UK', u'Cancer Research UK'),
                ('Center for Regional Policy Research and Cooperation (Studiorum)', u'Center for Regional Policy Research and Cooperation (Studiorum)'),
                ('CWMW', u'Center Women and Modern World (CWMW)'),
                ('KUZ-CAH', u'Coalition of Association of Healthcare (KUZ-CAH)'),
                ('Council of Occupational Therapists for the European Countries', u'Council of Occupational Therapists for the European Countries'),
                ('HUST', u'Croatian Association for Sanitary Engineering - Chamber of Sanitary Engineers & Technicians (HUSI)'),
                ('CTMA', u'Cyprus Turkish Medical Association (CTMA)'),
                ('Dachverband Komplementarmedizin', u'Dachverband Komplementarmedizin'),
		('EUROPA DONNA', u'EUROPA DONNA - The European Breast Cancer Coalition'),
                ('EATG', u'European AIDS Treatment Group (EATG)'),
                ('Eurocare', u'European Alcohol Policy Alliance (Eurocare)'),
                ('Eurosafe', u'European Association for Injury Prevention and Safety Promotion, European Child Safety Alliance (Eurosafe)'),
                ('EAHM', u'European Association of Hospital Managers (EAHM)'),
                ('EAHP', u'European Association of Hospital Pharmacists (EAHP)'),
                ('AEMH', u'European Association of Senior Hospital Physicians (AEMH)'),
                ('European CanCer Organisation', u'European CanCer Organisation'),
                ('ECCH', u'European Central Council of Homeopaths (ECCH)'),
                ('ECU', u'European Chiropractors\' Union (ECU)'),
                ('ECH', u'European Committee for Homeopathy (ECH)'),
                ('ECPM', u'European Council of Doctors for Plurality in Medicine (ECPM)'),
                ('European Council of Optometry and Optics', u'European Council of Optometry and Optics'),
                ('EFHPA', u'European Federation of Homeopathic Patients\' Associations (EFHPA)'),
                ('FEANTSA', u'European Federation of National Organisations Working with the Homeless (FEANTSA)'),
                ('EFN', u'European Federation of Nurses Associations (EFN)'),
                ('EFPAM', u'European Federation of Patients\' Associations for Anthroposophic Medicine (EFPAM)'),
                ('EFAD', u'European Federation of the Associations of Dieticians (EFAD)'),
                ('EHN', u'European Heart Network (EHN)'),
                ('EHA', u'European Hematology Association (EHA)'),
                ('EIWH', u'European Institute of Womens Health (EIWH)'),
                ('European Medical Students\' Association', u'European Medical Students\' Association'),
                ('ENSP', u'European Network for Smoking and Tobacco Prevention (ENSP)'),
                ('ER-WCPT', u'European Region of the World Confederation for Physical Therapy (ER-WCPT)'),
                ('ERS', u'European Respiratory Society (ERS)'),
                ('ERRC', u'European Roma Rights Centre (ERRC)'),
                ('European Scientific Working Group on Influenza (ESWI)', u'European Scientific Working Group on Influenza (ESWI)'),
                ('European Shiatsu Federation (ESF)', u'European Shiatsu Federation (ESF)'),
                ('European Society of Intensive Care Medicine (ESICM)', u'European Society of Intensive Care Medicine (ESICM)'),
                ('Fundacion de Ciencias del Medicamento y Productos Sanitarios (Fundamed)', u'Fundacion de Ciencias del Medicamento y Productos Sanitarios (Fundamed)'),
                ('Health Action International - Europe (HAI)', u'Health Action International - Europe (HAI)'),
                ('Health Action International looking for a Project Officer', u'Health Action International looking for a Project Officer'),
                ('International Centre of Health Protection (HERA)', u'International Centre of Health Protection (HERA)'),
                ('International Council of Medical Acupuncture and Related Techniques (ICMART)', u'International Council of Medical Acupuncture and Related Techniques (ICMART)'),
                ('International Diabetes Federation - European Region (IDF)', u'International Diabetes Federation - European Region (IDF)'),
                ('International Federation of Anthroposophical Medical Associations (IVAA)', u'International Federation of Anthroposophical Medical Associations (IVAA)'),
                ('International Planned Parenthood Federation - European Network (IPPF - EN)', u'International Planned Parenthood Federation - European Network (IPPF - EN)'),
                ('Italian Institute for Quality of Life (IVQ)', u'Italian Institute for Quality of Life (IVQ)'),
                ('Life Quality Improvement Organisation (FLIGHT/LET)', u'Life Quality Improvement Organisation (FLIGHT/LET)'),
                ('Malta Health Network (MHN)', u'Malta Health Network (MHN)'),
                ('Medecins du monde (MdM) - Doctors of the World International Network Head Office', u'Medecins du monde (MdM) - Doctors of the World International Network Head Office'),
                ('Mental Health Europe - Sante Mentale Europe (MHE-SME)', u'Mental Health Europe - Sante Mentale Europe (MHE-SME)'),
                ('National Health Alliance of Serbia and National Association of Emergency Medical Staff of Serbia (NAZS and NAzHMP)', u'National Health Alliance of Serbia and National Association of Emergency Medical Staff of Serbia (NAZS and NAzHMP)'),
                ('North West of England Region (NWE)', u'North West of England Region (NWE)'),
                ('Patient Fertility Association (CHEN)', u'Patient Fertility Association (CHEN)'),
                ('Pharmaceutical Group of the European Union (PGEU)', u'Pharmaceutical Group of the European Union (PGEU)'),
                ('PIN for Health', u'PIN for Health'),
                ('Polish Society for Health Programs (PSHP - PTPZ)', u'Polish Society for Health Programs (PSHP - PTPZ)'),
                ('Romtens Foundation', u'Romtens Foundation'),
                ('Royal College of Nursing (RCN)', u'Royal College of Nursing (RCN)'),
                ('Royal College of Physicians of London (RCP London)', u'Royal College of Physicians of London (RCP London)'),
                ('Royal National Institute of Blind People', u'Royal National Institute of Blind People'),
                ('SALUS Charitable Foundation', u'SALUS Charitable Foundation'),
		('Slovenian Coalition for Tobacco Control and Public Health (SCTC)', u'Slovenian Coalition for Tobacco Control and Public Health (SCTC)'),
		('Smoke Free Partnership (SFP)', u'Smoke Free Partnership (SFP)'),
		('SOS Health Association', u'SOS Health Association'),
		('Sustainable World Foundation', u'Sustainable World Foundation'),
		('Thalassaemia International Federation (TIF)', u'Thalassaemia International Federation (TIF)'),
		('The Association of Schools of Public Health in the European Union (ASPHER)', u'The Association of Schools of Public Health in the European Union (ASPHER)'),
		('The European Mens\' Health Forum (EMHF)', u'The European Mens\' Health Forum (EMHF)'),
		('The Genesis Association', u'The Genesis Association'),
		('The Health and Europe Centre', u'The Health and Europe Centre'),
		('The Union of Lithuanian Health Psychologists (ULHP)', u'The Union of Lithuanian Health Psychologists (ULHP)'),
		('Turkish Pharmacists\' Association', u'Turkish Pharmacists\' Association'),
		('Universal Education Foundation (UEF)', u'Universal Education Foundation (UEF)'),
		('Wiener Internationale Akademie fur Ganzheitsmedizin (gamed)', u'Wiener Internationale Akademie fur Ganzheitsmedizin (gamed)'),
		('World Cancer Research Fund International (WCRF)', u'World Cancer Research Fund International (WCRF)'),
		)
	),
	('UNDEF', (
		('Rajiv Shah - Administrator for United States Agency for International Development', u'Rajiv Shah - Administrator for United States Agency for International Development'),
		('Peter Baxter - Director General of Australian Agency for International Development', u'Peter Baxter - Director General of Australian Agency for International Development'),
		('Oscar Fernandez-Taranco - Assistant Secretary General for Department of Political Affairs', u'Oscar Fernandez-Taranco - Assistant Secretary General for Department of Political Affairs'),
		('Navanethem Pillay - UN High Commissioner for Human Rights', u'Navanethem Pillay - UN High Commissioner for Human Rights'),
		('Michelle Bachelet - Head of UN Women', u'Michelle Bachelet - Head of UN Women'),
		('Michael Doyle - Chair of UNDEF Advisory Board', u'Michael Doyle - Chair of UNDEF Advisory Board'),
		('Mark Gunter - Chairman of Equal Access', u'Mark Gunter - Chairman of Equal Access'),
		('Helen Clark - Administrator of UN Development Programme', u'Helen Clark - Administrator of UN Development Programme'),
		('Hardeep Singh Puri - Permanent Representative of India to the UN', u'Hardeep Singh Puri - Permanent Representative of India to the UN'),
		('Fernando Arias Gonzalez - Permanent Representative of Spain to UN', u'Fernando Arias Gonzalez - Permanent Representative of Spain to UN'),
		('Dr. Ulrich Schroder - Chief Executive Officer of German Development Bank', u'Dr. Ulrich Schroder - Chief Executive Officer of German Development Bank'),
		('Dr. Roland Rich - Executive Head', u'Dr. Roland Rich - Executive Head'),
		('Charlotte-Petru Gornitzka - Director-general of Swedish International Development Cooperation Agency', u'Charlotte-Petru Gornitzka - Director-general of Swedish International Development Cooperation Agency'),
		('Andrews Addoquaye Tagoe - Chairman of Youth Empowerment Synergy', u'Andrews Addoquaye Tagoe - Chairman of Youth Empowerment Synergy'),
		('Amir A. Dossai - Executive Director of UN Office for Partnerships', u'Amir A. Dossai - Executive Director of UN Office for Partnerships'),
		('Akihiko Tanaka - President of Japan International Cooperation Agency', u'Akihiko Tanaka - President of Japan International Cooperation Agency'),
		('Ahamad Mohammad Almuekhi - Director of Department of International Development Qatar', u'Ahamad Mohammad Almuekhi - Director of Department of International Development Qatar'),		
		)
	),
	('NFL', (
		('Trent Baalke - San Francisco 49ers', u'Trent Baalke - San Francisco 49ers'),
		('Tom Telesco - San Diago Chargers', u'Tom Telesco - San Diago Chargers'),
		('Thomas Dimitroff - Atlanta Falcons', u'Thomas Dimitroff - Atlanta Falcons'),
		('Ted Thompson - Green Bay Packers', u'Ted Thompson - Green Bay Packers'),
		('Steve Keim - Arizona Cardinals', u'Steve Keim - Arizona Cardinals'),
		('Ryan Grigson - Indianapolis Colts', u'Ryan Grigson - Indianapolis Colts'),
		('Ruston Webster - Tennessee Titans', u'Ruston Webster - Tennessee Titans'),
		('Rick Spielman - Minnesota Vikings', u'Rick Spielman - Minnesota Vikings'),
		('Rick Smith - Houston Texans', u'Rick Smith - Houston Texans'),
		('Reggie McKenzie - Oakland Raiders', u'Reggie McKenzie - Oakland Raiders'),
		('Phil Emery - Chicago Bears', u'Phil Emery - Chicago Bears'),
		('Ozzie Newsome - Baltimore Ravens', u'Ozzie Newsome - Baltimore Ravens'),
		('Mike Brown - Cincinnati Bengals', u'Mike Brown - Cincinnati Bengals'),
		('Mickey Loomis - New Orleans Saints', u'Mickey Loomis - New Orleans Saints'),
		('Michael Lombardi - Cleveland Browns', u'Michael Lombardi - Cleveland Browns'),
		('Martin Mayhew - Detroit Lions', u'Martin Mayhew - Detroit Lions'),
		('Mark Dominik - Tampa Bay Buccaneers', u'Mark Dominik - Tampa Bay Buccaneers'),
		('Les Snead - St. Louis Rams', u'Les Snead - St. Louis Rams'),
		('Kevin Colbert - Pittsburgh Steelers', u'Kevin Colbert - Pittsburgh Steelers'),
		('John Schneider - Seattle Seahawks', u'John Schneider - Seattle Seahawks'),
		('John Idzik Jr. - New York Jets', u'John Idzik Jr. - New York Jets'),
		('John Elway - Denver Broncos', u'John Elway - Denver Broncos'),
		('John Dorsey - Kansas City Chiefs', u'John Dorsey - Kansas City Chiefs'),
		('Jerry Reese - New York Giants', u'Jerry Reese - New York Giants'),
		('Jerry Jones - Dallas Cowboys', u'Jerry Jones - Dallas Cowboys'),
		('Jeff Ireland - Miami Dolphins', u'Jeff Ireland - Miami Dolphins'),
		('Howie Roseman - Philidelphia Eagles', u'Howie Roseman - Philidelphia Eagles'),
		('David Caldwell - Jacksonville Jaguars', u'David Caldwell - Jacksonville Jaguars'),
		('Dave Gettleman - Carolina Panthers', u'Dave Gettleman - Carolina Panthers'),
		('Buddy Nix - Buffalo Bills', u'Buddy Nix - Buffalo Bills'),
		('Bruce Allen - Washington Redskins', u'Bruce Allen - Washington Redskins'),
		('Bill Belichick - New England Patriots', u'Bill Belichick - New England Patriots'),	
		)
	),
	('Alliance of Automobile Manufacturers', (
		('BMW Group', u'BMW Group'),
		('Chrysler Group LLC', u'Chrysler Group LLC'),
		('Ford Motor Company', u'Ford Motor Company'),
		('General Motors', u'General Motors'),
		('Jaguar Land Rover', u'Jaguar Land Rover'),
		('Mazda', u'Mazda'),
		('Mercedes-Benz USA', u'Mercedes-Benz USA'),
		('Mitsubishi Motors', u'Mitsubishi Motors'),
		('Porsche Cars North America', u'Porsche Cars North America'),
		('Toyota', u'Toyota'),
		('Volkswagen Group of America', u'Volkswagen Group of America'),
		('Volvo Car Corporation', u'Volvo Car Corporation'),	
		)
	),
	('Tunisian Uprising', (
				('Ahmed Friaa - Interior Minister', u'Ahmed Friaa - Interior Minister'),
		('Ahmed Ibrahim - Leader of the Ettajdid Party', u'Ahmed Ibrahim - Leader of the Ettajdid Party'),
		('Ahmed Najib Chebbi - Leader of the PDP (Opposition)', u'Ahmed Najib Chebbi - Leader of the PDP (Opposition)'),
		('Amr Moussa - Secretary-General of the Arab League', u'Amr Moussa - Secretary-General of the Arab League'),
		('Fawzia Zouari - Journalist and Feminist', u'Fawzia Zouari - Journalist and Feminist'),
		('Fouad Mebazaa - Interim President of Tunisia', u'Fouad Mebazaa - Interim President of Tunisia'),
		('Hamadi Jebali - Secretary-General of the Ennahda Party', u'Hamadi Jebali - Secretary-General of the Ennahda Party'),
		('Houssine Dimassi - Militant in the UGTT', u'Houssine Dimassi - Militant in the UGTT'),
		('Lazhar Karoui Chebbi - Interim Minister of Justice', u'Lazhar Karoui Chebbi - Interim Minister of Justice'),
		('Mohamed Ghannouchi - Prime Minister of Tunisia', u'Mohamed Ghannouchi - Prime Minister of Tunisia'),
		('Mustapha ben Jaafar - Leader of Et-takatol (FDTL)', u'Mustapha ben Jaafar - Leader of Et-takatol (FDTL)'),
		('Rachid Amar - Chief of Army', u'Rachid Amar - Chief of Army'),
		('Yadh ben Acour - President of the Higher Political Reform Commission', u'Yadh ben Acour - President of the Higher Political Reform Commission'),
		)
	),
	('Newspaper Revolution', (
				('Alan Rusbridge', u'Alan Rusbridge'),
		('Arianna Huffington', u'Arianna Huffington'),
		('Dunja Mijatovic', u'Dunja Mijatovic'),
		('Eddy Hartenstein', u'Eddy Hartenstein'),
		('Hamad bin Thamer Al Thani', u'Hamad bin Thamer Al Thani'),
		('Indu Jain', u'Indu Jain'),
		('Jack Dorsey', u'Jack Dorsey'),
		('James Murdoch', u'James Murdoch'),
		('John Fallon', u'John Fallon'),
		('Ken Doctor', u'Ken Doctor'),
		('Larry Page', u'Larry Page'),
		('Mark Thompson', u'Mark Thompson'),
		('Tim Cook', u'Tim Cook'),
		('William T. Lake', u'William T. Lake'),
		('Zhang Yannong', u'Zhang Yannong'),
		)
	),
	('Ad-Hoc', (
				('Confidential #1', u'Confidential #1'),
		('Confidential #2', u'Confidential #2'),
		('Confidential #3', u'Confidential #3'),
		('Confidential #4', u'Confidential #4'),
		('Confidential #5', u'Confidential #5'),
		('Confidential #6', u'Confidential #6'),
		('Confidential #7', u'Confidential #7'),
		('Confidential #8', u'Confidential #8'),
		('Confidential #9', u'Confidential #9'),
		('Confidential #10', u'Confidential #10'),
		('Confidential #11', u'Confidential #11'),
		('Confidential #12', u'Confidential #12'),
		('Confidential #13', u'Confidential #13'),
		('Confidential #14', u'Confidential #14'),
		('Confidential #15', u'Confidential #15'),
		('Confidential #16', u'Confidential #16'),
		('Confidential #17', u'Confidential #17'),
		('Confidential #18', u'Confidential #18'),
		)
	),
	('Robin hood', (
		('Wereburga of the Woolmen', u'Wereburga of the Woolmen'),
		('Viscount Sernays of Stow-on-Tarn', u'Viscount Sernays of Stow-on-Tarn'),
		('Stonemasons - Anselmus', u'Stonemasons - Anselmus'),
		('Sir Guy of Gisborne', u'Sir Guy of Gisborne'),
		('Sheriff Tancred of Nottinghamshire', u'Sheriff Tancred of Nottinghamshire'),
		('Sergeant Rogerius of the Knight\'s Templar', u'Sergeant Rogerius of the Knight\'s Templar'),
		('Prioress Alianor of Abercaster Priori', u'Prioress Alianor of Abercaster Priori'),
		('Lyonel Mayor of Kingsbarrow', u'Lyonel Mayor of Kingsbarrow'),
		('Helisende of the Brewer\'s Guild', u'Helisende of the Brewer\'s Guild'),
		('Fawkes of the Carpenters', u'Fawkes of the Carpenters'),
		('Emelyne of the Weavers', u'Emelyne of the Weavers'),
		('Bishop Hubertus of Nottingham', u'Bishop Hubertus of Nottingham'),
		('Beringer of the Blacksmiths', u'Beringer of the Blacksmiths'),
		('Baron Pierce of Finry', u'Baron Pierce of Finry'),
		('Baron Joffrey of Dunkeld', u'Baron Joffrey of Dunkeld'),
		('Alderman Thorold', u'Alderman Thorold'),
		('Alderman Myghchaell', u'Alderman Myghchaell'),
		)
	),
	('Punic Wars', (
		('Aulus Atilius Calatinus', u'Aulus Atilius Calatinus'),
		('Aulus Postumius Albinus', u'Aulus Postumius Albinus'),
		('Gaius Flaminius Nepos', u'Gaius Flaminius Nepos'),
		('Gauis Caludius Centho', u'Gauis Caludius Centho'),
		('Lucius Caecilius Metellus', u'Lucius Caecilius Metellus'),
		('Lucius Manlius Vulso Longus', u'Lucius Manlius Vulso Longus'),
		('Marcus Claudius Marcellus', u'Marcus Claudius Marcellus'),
		('Marcus Minucius Rufus', u'Marcus Minucius Rufus'),
		('Publius Cornelius Scipo', u'Publius Cornelius Scipo'),
		('Quintus Fabius Maximus Verrucosus', u'Quintus Fabius Maximus Verrucosus'),
		('Tiberius Sempronius Gracchus', u'Tiberius Sempronius Gracchus'),
		('Titus Manlius Torquatus', u'Titus Manlius Torquatus'),
		)
	),
	('Korean War (North Korea)', (
		('Alexei Ivanovich Hegay', u'Alexei Ivanovich Hegay'),
		('Choe Yong-rim', u'Choe Yong-rim'),
		('Choi Yong-Kun', u'Choi Yong-Kun'),
		('Kim Chon-hae', u'Kim Chon-hae'),
		('Kim Il-Sung', u'Kim Il-Sung'),
		('Kim Sung-Ae', u'Kim Sung-Ae'),
		('Kim Tu-bong', u'Kim Tu-bong'),
		('Kim Yong-ju', u'Kim Yong-ju'),
		('Kim Yong-nam', u'Kim Yong-nam'),
		('Ni Zhiliang', u'Ni Zhiliang'),
		('O Chin-u', u'O Chin-u'),
		('Paek Hak-rim', u'Paek Hak-rim'),
		('Pak Hon-yong', u'Pak Hon-yong'),
		('Peng Teh-Huai', u'Peng Teh-Huai'),
		('Ri Yong-mu', u'Ri Yong-mu'),
		('Vasily Moskovsky', u'Vasily Moskovsky'),
		)
	),
	('Korean War (South Korea)', (
		('Syngman Rhee', u'Syngman Rhee'),
		('Son Won-il', u'Son Won-il'),
		('Shin Sung-mo', u'Shin Sung-mo'),
		('Shin Hyun-joon', u'Shin Hyun-joon'),
		('Rear Adm. Roscoe H. Hillenkoetter', u'Rear Adm. Roscoe H. Hillenkoetter'),
		('Paik Sun-yup', u'Paik Sun-yup'),
		('Paik In-Yeop', u'Paik In-Yeop'),
		('Matthew Bunker Ridgway', u'Matthew Bunker Ridgway'),
		('Major General O.P. Smith', u'Major General O.P. Smith'),
		('Major General Edward M. "Ned" Almond', u'Major General Edward M. "Ned" Almond'),
		('Lee Sungmin', u'Lee Sungmin'),
		('John J. Muccio', u'John J. Muccio'),
		('General Chung Il-kwon', u'General Chung Il-kwon'),
		('Chang Myon', u'Chang Myon'),
		('Captain Sir Vyvyan Holt', u'Captain Sir Vyvyan Holt'),
		('Air Force Commander', u'Air Force Commander'),
		)
	),
	('War of 1812 Canada', (
		('Charles de Salaberry', u'Charles de Salaberry'),
		('Francis de Rottenburg', u'Francis de Rottenburg'),
		('Henry Bathurst', u'Henry Bathurst'),
		('John Molson', u'John Molson'),
		('Joseph Berens', u'Joseph Berens'),
		('Joseph-Octave Plessis', u'Joseph-Octave Plessis'),
		('Robert Ross', u'Robert Ross'),
		('Roger Hale Sheaffe', u'Roger Hale Sheaffe'),
		('Sir Alexander Inglis Cochrane', u'Sir Alexander Inglis Cochrane'),
		('Sir Edward Pakenham', u'Sir Edward Pakenham'),
		('Sir George Prevost', u'Sir George Prevost'),
		('Sir Gordon Drummond', u'Sir Gordon Drummond'),
		('Sir Henry Bunbury', u'Sir Henry Bunbury'),
		('Sir Isaac Brock', u'Sir Isaac Brock'),
		('Sir John Sherbrooke', u'Sir John Sherbrooke'),
		('Tecumseh', u'Tecumseh'),
		('William Weatherford', u'William Weatherford'),
		)
	),
	('War of 1812 USA', (
		('Zebulon Pike', u'Zebulon Pike'),
		('Winfield Scott', u'Winfield Scott'),
		('William Hull', u'William Hull'),
		('William Henry Harrison', u'William Henry Harrison'),
		('William Eustis', u'William Eustis'),
		('Pushmataha', u'Pushmataha'),
		('Paul Hamilton', u'Paul Hamilton'),
		('Major Ridge (Pathkiller II)', u'Major Ridge (Pathkiller II)'),
		('John Armstrong, Jr.', u'John Armstrong, Jr.'),
		('James Monroe', u'James Monroe'),
		('Jacob Brown', u'Jacob Brown'),
		('Henry Dearborn', u'Henry Dearborn'),
		('Harrison Gray Otis', u'Harrison Gray Otis'),
		('George Clinton', u'George Clinton'),
		('Elbridge Gerry', u'Elbridge Gerry'),
		('Andrew Jackson', u'Andrew Jackson'),
		('Albert Gallatin', u'Albert Gallatin'),
		)
	),
)

ASSIGN_TYPE = (( True, 'Country'), (False, 'Character'))

