# This is used for country/character assignments, not the one in mcmun.constants

COUNTRIES_CHARACTER = (

("Countries", (
		("AFL-CIO, USA", u"AFL-CIO, USA"), 
		("ALECSO", u"ALECSO"), 
		("Afghanistan", u"Afghanistan"), 
		("Albania", u"Albania"), 
		("Algeria", u"Algeria"), 
		("All India Organisation of Employers", u"All India Organisation of Employers"), 
		("All-China Federation of Trade Unions", u"All-China Federation of Trade Unions"), 
		("All-Russian Confederation of Labour", u"All-Russian Confederation of Labour"), 
		("Amnesty International", u"Amnesty International"), 
		("Andorra", u"Andorra"), 
		("Angola", u"Angola"), 
		("Antigua and Barbuda", u"Antigua and Barbuda"), 
		("Argentina", u"Argentina"), 
		("Armenia", u"Armenia"), 
		("Aruba", u"Aruba"), 
		("Asociacion Nacional de Empresarios de Colombia", u"Asociacion Nacional de Empresarios de Colombia"), 
		("Australia", u"Australia"), 
		("Austria", u"Austria"), 
		("Azerbaijan", u"Azerbaijan"), 
		("BP", u"BP"), 
		("BRIDGE", u"BRIDGE"), 
		("Bahamas", u"Bahamas"), 
		("Bahrain", u"Bahrain"), 
		("Bangladesh", u"Bangladesh"), 
		("Bangladesh Employers' Federation", u"Bangladesh Employers' Federation"), 
		("Bangladesh Free Trade Union Congress", u"Bangladesh Free Trade Union Congress"), 
		("Barbados", u"Barbados"), 
		("Belarus", u"Belarus"), 
		("Belgium", u"Belgium"), 
		("Belize", u"Belize"), 
		("Benin", u"Benin"), 
		("Bhutan", u"Bhutan"), 
		("Bolivia", u"Bolivia"), 
		("Bosnia and Herzegovina", u"Bosnia and Herzegovina"), 
		("Botswana", u"Botswana"), 
		("Botswana Confederation of Commerce, Industry, and Manpower", u"Botswana Confederation of Commerce, Industry, and Manpower"), 
		("Botswana Federation of Trade Unions", u"Botswana Federation of Trade Unions"), 
		("Brazil", u"Brazil"), 
		("Brunei", u"Brunei"), 
		("Bulgaria", u"Bulgaria"), 
		("Burkina Faso", u"Burkina Faso"), 
		("Burundi", u"Burundi"), 
		("Business Unity South Africa", u"Business Unity South Africa"), 
		("C\u00f4te d'Ivoire", u"C\u00f4te d'Ivoire"), 
		("CDC", u"CDC"), 
		("Camara de Industrias de Guayaquil", u"Camara de Industrias de Guayaquil"), 
		("Cambodia", u"Cambodia"), 
		("Cameroon", u"Cameroon"), 
		("Canada", u"Canada"), 
		("Canadian Employers' Council", u"Canadian Employers' Council"), 
		("Canadian labour Congress", u"Canadian labour Congress"), 
		("Cape Verde", u"Cape Verde"), 
		("Central African Republic", u"Central African Republic"), 
		("Central Organisation of Free Trade Unions, Uganda (COFTU)", u"Central Organisation of Free Trade Unions, Uganda (COFTU)"), 
		("Central Organization of Trade Unions (Kenya)", u"Central Organization of Trade Unions (Kenya)"), 
		("Central Union of Workers, Colombia", u"Central Union of Workers, Colombia"), 
		("Centre of Indian Trade Unions", u"Centre of Indian Trade Unions"), 
		("Chad", u"Chad"), 
		("Chevron", u"Chevron"), 
		("Chile", u"Chile"), 
		("China", u"China"), 
		("China Enterprise Confederation", u"China Enterprise Confederation"), 
		("Chinese Taipei Federation of Industries", u"Chinese Taipei Federation of Industries"), 
		("Colombia", u"Colombia"), 
		("Comoros", u"Comoros"), 
		("Confederacao Nacional da Industria", u"Confederacao Nacional da Industria"), 
		("Confederacion Patronal de la Republica Mexicana", u"Confederacion Patronal de la Republica Mexicana"), 
		("Confederacion de la Produccion y del Comercio", u"Confederacion de la Produccion y del Comercio"), 
		("Confederation of British Industry", u"Confederation of British Industry"), 
		("Confederation of German Employers", u"Confederation of German Employers"), 
		("Confederation of Indonesia Prosperous Trade Union", u"Confederation of Indonesia Prosperous Trade Union"), 
		("Confederation of Netherlands Industry and Employers", u"Confederation of Netherlands Industry and Employers"), 
		("Confederation of Public Workers' Unions (Turkey)", u"Confederation of Public Workers' Unions (Turkey)"), 
		("Confederation of Workers of Venezuela", u"Confederation of Workers of Venezuela"), 
		("Congo", u"Congo"), 
		("Congress of South African Trade Unions", u"Congress of South African Trade Unions"), 
		("Conseil national du Patronat Burkinabe", u"Conseil national du Patronat Burkinabe"), 
		("Consejo Superior de la Empresa Privada", u"Consejo Superior de la Empresa Privada"), 
		("Costa Rica", u"Costa Rica"), 
		("Council of Saudi Chambers", u"Council of Saudi Chambers"), 
		("Croatia", u"Croatia"), 
		("Cuba", u"Cuba"), 
		("Curacao", u"Curacao"), 
		("Cyprus", u"Cyprus"), 
		("Czech Republic", u"Czech Republic"), 
		("Democratic People's Republic of Korea", u"Democratic People's Republic of Korea"), 
		("Democratic Republic of Congo", u"Democratic Republic of Congo"), 
		("Denmark", u"Denmark"), 
		("Dijibouti", u"Dijibouti"), 
		("Dominican Republic", u"Dominican Republic"), 
		("EFSA", u"EFSA"), 
		("EMEA", u"EMEA"), 
		("ENVI", u"ENVI"), 
		("Ecuador", u"Ecuador"), 
		("Ecuador Confederation of Free Trade Union Organizations", u"Ecuador Confederation of Free Trade Union Organizations"), 
		("Egypt", u"Egypt"), 
		("Egyptian Trade Union Federation", u"Egyptian Trade Union Federation"), 
		("El Salvador", u"El Salvador"), 
		("Employers' Federation of Ceylon (Sri Lanka)", u"Employers' Federation of Ceylon (Sri Lanka)"), 
		("Employers' Federation of Pakistan", u"Employers' Federation of Pakistan"), 
		("Employers' Organizations", u"Employers' Organizations"), 
		("Equitorial Guinea", u"Equitorial Guinea"), 
		("Eritrea", u"Eritrea"), 
		("Estonia", u"Estonia"), 
		("Ethiopia", u"Ethiopia"), 
		("European Medicines Agency", u"European Medicines Agency"), 
		("ExxonMobil", u"ExxonMobil"), 
		("Federacion de camaras y Asociaciones de Comercio y Produccion de Venezuela", u"Federacion de camaras y Asociaciones de Comercio y Produccion de Venezuela"), 
		("Federated States of Micronesia", u"Federated States of Micronesia"), 
		("Federation Dutch Labour Movement", u"Federation Dutch Labour Movement"), 
		("Federation des Entreprises du Congo", u"Federation des Entreprises du Congo"), 
		("Federation of American Women's Clubs Overseas", u"Federation of American Women's Clubs Overseas"), 
		("Federation of Egyptian Industries", u"Federation of Egyptian Industries"), 
		("Federation of Kenya Employers", u"Federation of Kenya Employers"), 
		("Federation of Korean Trade Unions", u"Federation of Korean Trade Unions"), 
		("Federation of Oil Unions in Iraq", u"Federation of Oil Unions in Iraq"), 
		("Federation of Trade Unions of the Republic of Kazakhstan", u"Federation of Trade Unions of the Republic of Kazakhstan"), 
		("Federation of Uganda Employers", u"Federation of Uganda Employers"), 
		("Fiji", u"Fiji"), 
		("Finland", u"Finland"), 
		("France", u"France"), 
		("French Democratic Confederation of Labour", u"French Democratic Confederation of Labour"), 
		("Gabon", u"Gabon"), 
		("Gambia", u"Gambia"), 
		("General Confederation of Peruvian Workers (CGTP)", u"General Confederation of Peruvian Workers (CGTP)"), 
		("General Federation of Jordanian Trade Unions", u"General Federation of Jordanian Trade Unions"), 
		("General Federation of Trade Unions (Syria)", u"General Federation of Trade Unions (Syria)"), 
		("General Federation of Trade Unions (UK)", u"General Federation of Trade Unions (UK)"), 
		("Georgia", u"Georgia"), 
		("German Christian Workers' Federation", u"German Christian Workers' Federation"), 
		("Germany", u"Germany"), 
		("Ghana", u"Ghana"), 
		("Ghana Employers' Association", u"Ghana Employers' Association"), 
		("Greece", u"Greece"), 
		("Greenpeace", u"Greenpeace"), 
		("Grenada", u"Grenada"), 
		("Guam", u"Guam"), 
		("Guatemala", u"Guatemala"), 
		("Guinea", u"Guinea"), 
		("Guinea - Bissau", u"Guinea - Bissau"), 
		("Guyana", u"Guyana"), 
		("Haiti", u"Haiti"), 
		("Honduras", u"Honduras"), 
		("Hong Kong, China", u"Hong Kong, China"), 
		("Hungary", u"Hungary"), 
		("Husky", u"Husky"), 
		("Iceland", u"Iceland"), 
		("Imperial", u"Imperial"), 
		("India", u"India"), 
		("Indonesia", u"Indonesia"), 
		("International Federation of Red Cross and Red Crescent Societies", u"International Federation of Red Cross and Red Crescent Societies"), 
		("International Service for Human Rights", u"International Service for Human Rights"), 
		("Iran", u"Iran"), 
		("Iranian Confederation of Employers' Associations", u"Iranian Confederation of Employers' Associations"), 
		("Iraq", u"Iraq"), 
		("Ireland", u"Ireland"), 
		("Israel", u"Israel"), 
		("Italian Confederation of Workers' Trade Union", u"Italian Confederation of Workers' Trade Union"), 
		("Italy", u"Italy"), 
		("Jamaica", u"Jamaica"), 
		("Japan", u"Japan"), 
		("Japan Business Federation", u"Japan Business Federation"), 
		("Jordan", u"Jordan"), 
		("Kazakhstan", u"Kazakhstan"), 
		("Kenya", u"Kenya"), 
		("Kuwait", u"Kuwait"), 
		("Kyrgyzstan", u"Kyrgyzstan"), 
		("Lao People's Democratic Republic", u"Lao People's Democratic Republic"), 
		("Latvia", u"Latvia"), 
		("Lebanon", u"Lebanon"), 
		("Lesotho", u"Lesotho"), 
		("Liberia", u"Liberia"), 
		("Libya", u"Libya"), 
		("Liechtenstein", u"Liechtenstein"), 
		("Lithuania", u"Lithuania"), 
		("Luxembourg", u"Luxembourg"), 
		("Macao, China", u"Macao, China"), 
		("Madagascar", u"Madagascar"), 
		("Malawi", u"Malawi"), 
		("Malaysia", u"Malaysia"), 
		("Maldives", u"Maldives"), 
		("Mali", u"Mali"), 
		("Malta", u"Malta"), 
		("Marshall Islands", u"Marshall Islands"), 
		("Mauritania", u"Mauritania"), 
		("Mauritius", u"Mauritius"), 
		("Mexico", u"Mexico"), 
		("Monaco", u"Monaco"), 
		("Mongolia", u"Mongolia"), 
		("Montenegro", u"Montenegro"), 
		("Morocco", u"Morocco"), 
		("Mouvement des Entreprises de France", u"Mouvement des Entreprises de France"), 
		("Mozambique", u"Mozambique"), 
		("Myanmar", u"Myanmar"), 
		("Namibia", u"Namibia"), 
		("National Confederation of Workers of Burkina", u"National Confederation of Workers of Burkina"), 
		("National Trade Unions' Federation (Libya)", u"National Trade Unions' Federation (Libya)"), 
		("National Union of Congolese Workers", u"National Union of Congolese Workers"), 
		("National Union of General Workers (Japan)", u"National Union of General Workers (Japan)"), 
		("National Union of Mine and Metal Workers of the Mexican Republic", u"National Union of Mine and Metal Workers of the Mexican Republic"), 
		("National Union of Workers (Sri Lanka)", u"National Union of Workers (Sri Lanka)"), 
		("Nauru", u"Nauru"), 
		("Nepal", u"Nepal"), 
		("Netherlands", u"Netherlands"), 
		("New Caledonia", u"New Caledonia"), 
		("New Zealand", u"New Zealand"), 
		("Nicaragua", u"Nicaragua"), 
		("Nicaraguan Workers' Centre", u"Nicaraguan Workers' Centre"), 
		("Niger", u"Niger"), 
		("Nigeria", u"Nigeria"), 
		("Nigeria Employers' Consultative Association", u"Nigeria Employers' Consultative Association"), 
		("Northern Mariana Islands", u"Northern Mariana Islands"), 
		("Norway", u"Norway"), 
		("Oman", u"Oman"), 
		("PEPFAR", u"PEPFAR"), 
		("Pakistan", u"Pakistan"), 
		("Pakistan Workers Confederation", u"Pakistan Workers Confederation"), 
		("Palau", u"Palau"), 
		("Palestine", u"Palestine"), 
		("Panama", u"Panama"), 
		("Papa New Guinea", u"Papa New Guinea"), 
		("Paraguay", u"Paraguay"), 
		("Partners in Population Development", u"Partners in Population Development"), 
		("Peru", u"Peru"), 
		("Philippines", u"Philippines"), 
		("Poland", u"Poland"), 
		("Portugal", u"Portugal"), 
		("Qatar", u"Qatar"), 
		("Republic of Korea", u"Republic of Korea"), 
		("Republic of Macedonia", u"Republic of Macedonia"), 
		("Republic of Moldova", u"Republic of Moldova"), 
		("Romania", u"Romania"), 
		("Russian Federation", u"Russian Federation"), 
		("Russian Union of Industrialists and Entrepreneurs", u"Russian Union of Industrialists and Entrepreneurs"), 
		("Rwanda", u"Rwanda"), 
		("Saint Kitts and Nevis", u"Saint Kitts and Nevis"), 
		("Saint Lucia", u"Saint Lucia"), 
		("Saint Maarten", u"Saint Maarten"), 
		("Saint Vincent and the Grenadines", u"Saint Vincent and the Grenadines"), 
		("Samoa", u"Samoa"), 
		("San Marino", u"San Marino"), 
		("Saudi Arabia", u"Saudi Arabia"), 
		("Senegal", u"Senegal"), 
		("Serbia", u"Serbia"), 
		("Seychelles", u"Seychelles"), 
		("Shell", u"Shell"), 
		("Sierra Leone", u"Sierra Leone"), 
		("Sierra Leone Labour Congress", u"Sierra Leone Labour Congress"), 
		("Singapore", u"Singapore"), 
		("Slovakia", u"Slovakia"), 
		("Slovenia", u"Slovenia"), 
		("Solomon Islands", u"Solomon Islands"), 
		("Somalia", u"Somalia"), 
		("South Africa", u"South Africa"), 
		("South Sudan", u"South Sudan"), 
		("Spain", u"Spain"), 
		("Sri Lanka", u"Sri Lanka"), 
		("Sudan", u"Sudan"), 
		("Surimane", u"Surimane"), 
		("Swaziland", u"Swaziland"), 
		("Sweden", u"Sweden"), 
		("Swiss Federation of Trade Unions", u"Swiss Federation of Trade Unions"), 
		("Switzerland", u"Switzerland"), 
		("Syrian Arab Republic", u"Syrian Arab Republic"), 
		("Taiwan Confederation of Trade Unions", u"Taiwan Confederation of Trade Unions"), 
		("Tajikistan", u"Tajikistan"), 
		("Talisman Energy", u"Talisman Energy"), 
		("Thailand", u"Thailand"), 
		("The Employers' Association of Indonesia", u"The Employers' Association of Indonesia"), 
		("The Trades Union Congress of Ghana", u"The Trades Union Congress of Ghana"), 
		("Timor-Leste", u"Timor-Leste"), 
		("Togo", u"Togo"), 
		("Tonga", u"Tonga"), 
		("Trinidad and Tobago", u"Trinidad and Tobago"), 
		("Tulavu", u"Tulavu"), 
		("Tunisia", u"Tunisia"), 
		("Turkey", u"Turkey"), 
		("Turkish Confederation of Employer Associations", u"Turkish Confederation of Employer Associations"), 
		("Turkmenistan", u"Turkmenistan"), 
		("UN Body on Petroleum", u"UN Body on Petroleum"), 
		("Uganda", u"Uganda"), 
		("Ukraine", u"Ukraine"), 
		("Unified Workers' Central, Brazil", u"Unified Workers' Central, Brazil"), 
		("Union Patronale Suisse", u"Union Patronale Suisse"), 
		("Union of Workers in Industry, Garages, Construction Firms, Mines, and Printers (Rwanda)", u"Union of Workers in Industry, Garages, Construction Firms, Mines, and Printers (Rwanda)"), 
		("United Arab Emirates", u"United Arab Emirates"), 
		("United Kingdom", u"United Kingdom"), 
		("United Republic of Tanzania", u"United Republic of Tanzania"), 
		("United States Council for International Business", u"United States Council for International Business"), 
		("United States of America", u"United States of America"), 
		("Uruguay", u"Uruguay"), 
		("Uzbekistan", u"Uzbekistan"), 
		("VSO", u"VSO"), 
		("Vanuatu", u"Vanuatu"), 
		("Venezuela", u"Venezuela"), 
		("Viet Nam", u"Viet Nam"), 
		("WHO", u"WHO"), 
		("Workers' Central Union of Cuba", u"Workers' Central Union of Cuba"), 
		("Workers' House of the Islamic Republic of Iran", u"Workers' House of the Islamic Republic of Iran"), 
		("Workers' United Centre of Chile", u"Workers' United Centre of Chile"), 
		("World Trade Organization", u"World Trade Organization"), 
		("Yemen", u"Yemen"), 
		("Zambia", u"Zambia"), 
		("Zimbabwe", u"Zimbabwe"), 
		)
),
("FIFA", (
		("\u00dcnal Aysal", u"\u00dcnal Aysal"), 
		("Alan Bowkett", u"Alan Bowkett"), 
		("Alfonso Garcia Gabarron", u"Alfonso Garcia Gabarron"), 
		("Andrea Agnelli", u"Andrea Agnelli"), 
		("Angel Maria Villar Llona", u"Angel Maria Villar Llona"), 
		("Anthony Lake", u"Anthony Lake"), 
		("Dmitry Rybolovlev", u"Dmitry Rybolovlev"), 
		("Dr. Reinhard Rauball", u"Dr. Reinhard Rauball"), 
		("Florentino P\u00e9rez", u"Florentino P\u00e9rez"), 
		("Fr\u00e9d\u00e9ric Thiriez", u"Fr\u00e9d\u00e9ric Thiriez"), 
		("Fritz Keller", u"Fritz Keller"), 
		("HRH Prince William, The Duke of Cambridge", u"HRH Prince William, The Duke of Cambridge"), 
		("Hamad bin Thamer Al Thani", u"Hamad bin Thamer Al Thani"), 
		("Hans-Joachim Watzke", u"Hans-Joachim Watzke"), 
		("Henk Kivits", u"Henk Kivits"), 
		("Hennie Henrichs", u"Hennie Henrichs"), 
		("Igor Landau", u"Igor Landau"), 
		("Javier Tebas", u"Javier Tebas"), 
		("Jean-Fran\u00e7ois van Boxmeer", u"Jean-Fran\u00e7ois van Boxmeer"), 
		("Josep Maria Bartomeu", u"Josep Maria Bartomeu"), 
		("Julio Grondona", u"Julio Grondona"), 
		("Karl Hopfner", u"Karl Hopfner"), 
		("Khaldoon Al Mubarak", u"Khaldoon Al Mubarak"), 
		("Luca Campedelli", u"Luca Campedelli"), 
		("Malcom Glazer", u"Malcom Glazer"), 
		("Maurizio Beretta", u"Maurizio Beretta"), 
		("Michel Platini", u"Michel Platini"), 
		("Nasser Al-Khelaifi", u"Nasser Al-Khelaifi"), 
		("Phil Knight", u"Phil Knight"), 
		("Piara Powar", u"Piara Powar"), 
		("Pierre-Marie Geronimi", u"Pierre-Marie Geronimi"), 
		("Richard N. Haythornthwaite", u"Richard N. Haythornthwaite"), 
		("Roman Abramovich", u"Roman Abramovich"), 
		("Sepp Blatter", u"Sepp Blatter"), 
		("Silvio Berlusconi", u"Silvio Berlusconi"), 
		("Sir David Richards", u"Sir David Richards"), 
		("Steve Burke", u"Steve Burke"), 
		)
),
("DEGAULLE", (
		("Andre Malraux", u"Andre Malraux"), 
		("Bernard Cornut-Gentille", u"Bernard Cornut-Gentille"), 
		("Boegner, Jean-Marie", u"Boegner, Jean-Marie"), 
		("Cabanier, Admiral Georges", u"Cabanier, Admiral Georges"), 
		("Carbonnel, Eric C.M. de", u"Carbonnel, Eric C.M. de"), 
		("Couve de Murville, Maurice", u"Couve de Murville, Maurice"), 
		("Edouard Ramonet", u"Edouard Ramonet"), 
		("Ely general paul H.R", u"Ely general paul H.R"), 
		("Emile Pelletier", u"Emile Pelletier"), 
		("Faure, Maurice", u"Faure, Maurice"), 
		("Guillamat, Pierre", u"Guillamat, Pierre"), 
		("Herve Alphand", u"Herve Alphand"), 
		("Jacques Soustelle", u"Jacques Soustelle"), 
		("Joxe, Louis", u"Joxe, Louis"), 
		("Laloy,Jean", u"Laloy,Jean"), 
		("Lucet, Charles", u"Lucet, Charles"), 
		("Martin, General Andre", u"Martin, General Andre"), 
		("Max Lejeune", u"Max Lejeune"), 
		("Michel Debre", u"Michel Debre"), 
		("Mollet, Guy", u"Mollet, Guy"), 
		("Paul Bacon", u"Paul Bacon"), 
		("Pflimlin, Pierre", u"Pflimlin, Pierre"), 
		("Pinay, Antoine", u"Pinay, Antoine"), 
		("Pineau, Christian", u"Pineau, Christian"), 
		("Wormser, Olivier", u"Wormser, Olivier"), 
		("de Courcel, Geoffrey Chodron", u"de Courcel, Geoffrey Chodron"), 
		("valery, Francois", u"valery, Francois"), 
		)
),
("IRAN", (
		("Anne Armstrong", u"Anne Armstrong"), 
		("Caspar Weinberger", u"Caspar Weinberger"), 
		("Donald Regan", u"Donald Regan"), 
		("Edwin Meese III", u"Edwin Meese III"), 
		("Elliot Abrams", u"Elliot Abrams"), 
		("General Richard Secord", u"General Richard Secord"), 
		("George H.W. Bush", u"George H.W. Bush"), 
		("George Schultz", u"George Schultz"), 
		("James Brady", u"James Brady"), 
		("John Poindexter", u"John Poindexter"), 
		("Michael Ledeen", u"Michael Ledeen"), 
		("Oliver North", u"Oliver North"), 
		("Richard Brenneke", u"Richard Brenneke"), 
		("Thomas Clines", u"Thomas Clines"), 
		("William Casey", u"William Casey"), 
		)
),
("CAP", (
		("Andrew Delisle", u"Andrew Delisle"), 
		("Bertha Allen", u"Bertha Allen"), 
		("D'Arcy McNickle", u"D'Arcy McNickle"), 
		("David Ahenakew", u"David Ahenakew"), 
		("Elizabeth Isbister", u"Elizabeth Isbister"), 
		("Elsie Knott", u"Elsie Knott"), 
		("Eva Rickard", u"Eva Rickard"), 
		("George Manuel", u"George Manuel"), 
		("Harold Cardinal", u"Harold Cardinal"), 
		("John Turner", u"John Turner"), 
		("Judd Buchanan", u"Judd Buchanan"), 
		("Louis Karonaiktajeh Hall", u"Louis Karonaiktajeh Hall"), 
		("Mary Two-Axe Earley", u"Mary Two-Axe Earley"), 
		("Maxim Gros-Louis", u"Maxim Gros-Louis"), 
		("Morris Thompson", u"Morris Thompson"), 
		("Noel Doucette", u"Noel Doucette"), 
		("Oodgeroo Noonuccal", u"Oodgeroo Noonuccal"), 
		("Robert Bourassa", u"Robert Bourassa"), 
		("Tagek Curley", u"Tagek Curley"), 
		("Walter Deiter", u"Walter Deiter"), 
		)
),
("BNW", (
		("Arch-Community-songster", u"Arch-Community-songster"), 
		("Chancellor of Ford University", u"Chancellor of Ford University"), 
		("Commissioner of Eurasian Police Force", u"Commissioner of Eurasian Police Force"), 
		("Deputy Director of the Hatchery and Conditioning Centre, Conditioning Division", u"Deputy Director of the Hatchery and Conditioning Centre, Conditioning Division"), 
		("Director of Hatcheries and Conditioning", u"Director of Hatcheries and Conditioning"), 
		("Director of Health and Wellness Service", u"Director of Health and Wellness Service"), 
		("Director of the Central Eurasia Bank", u"Director of the Central Eurasia Bank"), 
		("Director of the Department of agriculture and mining", u"Director of the Department of agriculture and mining"), 
		("Director of the Eurasia Media Centre", u"Director of the Eurasia Media Centre"), 
		("Minister of Foreign Affairs", u"Minister of Foreign Affairs"), 
		("Minister of defense", u"Minister of defense"), 
		("Warden of the Savage Reservation", u"Warden of the Savage Reservation"), 
		)
),
("AMAZON", (
		("Alain Monie", u"Alain Monie"), 
		("Andrew R. Jassy", u"Andrew R. Jassy"), 
		("David A. Zapolsky", u"David A. Zapolsky"), 
		("Diego Piacentini", u"Diego Piacentini"), 
		("Dr. Werner Vogels", u"Dr. Werner Vogels"), 
		("James S. Gorelick", u"James S. Gorelick"), 
		("Jeffrey A. Wilke", u"Jeffrey A. Wilke"), 
		("Jeffrey M. Blackburn", u"Jeffrey M. Blackburn"), 
		("Jeffrey P. Bezos", u"Jeffrey P. Bezos"), 
		("John Seely Brown", u"John Seely Brown"), 
		("Johnathan J. Rubinstein", u"Johnathan J. Rubinstein"), 
		("Patricia Q. Stonesifer", u"Patricia Q. Stonesifer"), 
		("Sebastian J. Gunningham", u"Sebastian J. Gunningham"), 
		("Shelley L. Reynolds", u"Shelley L. Reynolds"), 
		("Steven Kessel", u"Steven Kessel"), 
		("Thomas J. Szkutak", u"Thomas J. Szkutak"), 
		("Thomas O. Ryder", u"Thomas O. Ryder"), 
		("Tom A. Alberg", u"Tom A. Alberg"), 
		("William B. (Bing) Gordon", u"William B. (Bing) Gordon"), 
		)
),
("Orange 1", (
		("CEO of Ukrinform - state-run news agency", u"CEO of Ukrinform - state-run news agency"), 
		("Chief of General Staff - Sergiy Kirichenko", u"Chief of General Staff - Sergiy Kirichenko"), 
		("Foreign Intelligence Service of Ukraine - Oleh HryhorovychSyniansy", u"Foreign Intelligence Service of Ukraine - Oleh HryhorovychSyniansy"), 
		("Gennadiy Bogolyubov", u"Gennadiy Bogolyubov"), 
		("Military Advisor - Igor Nirieych", u"Military Advisor - Igor Nirieych"), 
		("Military Advisor - Oleksandr Zatynayko", u"Military Advisor - Oleksandr Zatynayko"), 
		("Minister of Defence - Anatoliy Hrytsenko", u"Minister of Defence - Anatoliy Hrytsenko"), 
		("Minister of Economy - Arseniy Yatsenyuk", u"Minister of Economy - Arseniy Yatsenyuk"), 
		("Minister of European Integration - Hukejk Ravigja", u"Minister of European Integration - Hukejk Ravigja"), 
		("Minister of Foreign Affairs - Nasemu Ujisycka", u"Minister of Foreign Affairs - Nasemu Ujisycka"), 
		("Minister of Internal Affairs - Yuriy Vitaliyovych Lutsenko", u"Minister of Internal Affairs - Yuriy Vitaliyovych Lutsenko"), 
		("Minister of Justice - Yuriy Yekhanurov", u"Minister of Justice - Yuriy Yekhanurov"), 
		("Minister of Social Policy - Vyacheslav Kyrylenko", u"Minister of Social Policy - Vyacheslav Kyrylenko"), 
		("Prime Minister - Yulia Tymoshenko", u"Prime Minister - Yulia Tymoshenko"), 
		)
),
("Orange 2", (
		("Anatoliy Zlenko - Foreign Affairs", u"Anatoliy Zlenko - Foreign Affairs"), 
		("General Yuri Oriov - Military Advisor (Russian)", u"General Yuri Oriov - Military Advisor (Russian)"),
		("General Vitali Govrachych - Military Advisor (Ukrainian)", u"General Vitali Govrachych - Military Advisor (Ukrainian)"), 
		("General Volodymyr Shkidchenko - Defence", u"General Volodymyr Shkidchenko - Defence"), 
		("Sergei Lebedev - Military Advisor (Russian)", u"Sergei Lebedev - Military Advisor (Russian)"), 
		("Ivan Kyrylenko - Deputy Prime Minister", u"Ivan Kyrylenko - Deputy Prime Minister"), 
		("Mykola Azarov - Chairman of the Party", u"Mykola Azarov - Chairman of the Party"), 
		("Olehsandr Lavrynobych - Justice", u"Olehsandr Lavrynobych - Justice"), 
		("Oleksandr Yefremov - Deputy Chairman of the Party of Regions on Relations with the Parliament of Ukraine. (DCPRRPU)", u"Oleksandr Yefremov - Deputy Chairman of the Party of Regions on Relations with the Parliament of Ukraine. (DCPRRPU)"), 
		("Runit Akhmetov Ukrainian Billionaire", u"Runit Akhmetov Ukrainian Billionaire"), 
		("Sergey Kurchenko - Gas King Media Mogul (Ukrainian) - Long Term Backer of Yanukovitch", u"Sergey Kurchenko - Gas King Media Mogul (Ukrainian) - Long Term Backer of Yanukovitch"), 
		("Vadim Novinsky - Ukrainian Business Man", u"Vadim Novinsky - Ukrainian Business Man"), 
		("Valery Khoroshkovsky - Economy and European Integrations", u"Valery Khoroshkovsky - Economy and European Integrations"), 
		("Yevhen Petrovych - Political Advisor to Yanikovitch", u"Yevhen Petrovych - Political Advisor to Yanikovitch"), 
		("Yury Smimov - Interior Affairs", u"Yury Smimov - Interior Affairs"),
		("Vasyl Dzharty - Interior Affairs", u"Vasyl Dzharty - Interior Affairs"), 
		)
),
("RFE", (
		("Abdulrachmann (Abo) Fatalibey", u"Abdulrachmann (Abo) Fatalibey"), 
		("Admiral Harold B. Miller", u"Admiral Harold B. Miller"), 
		("Arthur W. Page", u"Arthur W. Page"), 
		("Bernard Yarrow", u"Bernard Yarrow"), 
		("Blagoy Dimov", u"Blagoy Dimov"), 
		("Cord Meyer", u"Cord Meyer"), 
		("Dragos Ungur", u"Dragos Ungur"), 
		("Emil Csonka", u"Emil Csonka"), 
		("Ferdinand Peroutka", u"Ferdinand Peroutka"), 
		("Frank Altschul", u"Frank Altschul"), 
		("Gyula Borbandi", u"Gyula Borbandi"), 
		("Gyula Dessewffy", u"Gyula Dessewffy"), 
		("Henry Ford II", u"Henry Ford II"), 
		("Herbert Gross", u"Herbert Gross"), 
		("Istvan Deak", u"Istvan Deak"), 
		("Jan Nowak-Jezioranski", u"Jan Nowak-Jezioranski"), 
		("Jaroslav Jan Endrst", u"Jaroslav Jan Endrst"), 
		("Julius Firt", u"Julius Firt"), 
		("Konrad Kellen", u"Konrad Kellen"), 
		("Oskar R. lange", u"Oskar R. lange"), 
		("Paul Henze", u"Paul Henze"), 
		("Pavel Tigrid", u"Pavel Tigrid"), 
		("Ralph E. Walter", u"Ralph E. Walter"), 
		("Richard Condon", u"Richard Condon"), 
		("Robert E. Lang", u"Robert E. Lang"), 
		("Rustam Ayanov(Kazakh Division)", u"Rustam Ayanov(Kazakh Division)"), 
		("Whitney Shepardson", u"Whitney Shepardson"), 
		("Wiktor Troscianko", u"Wiktor Troscianko"), 
		("Willam E. Griffith", u"Willam E. Griffith"), 
		("Zbigniew Brzezinski", u"Zbigniew Brzezinski"), 
		("Zoltan Szabo", u"Zoltan Szabo"), 
		)
),
("IRAQ", (
		("Andrew Card", u"Andrew Card"), 
		("Colin Powell", u"Colin Powell"), 
		("Condolezza Rice", u"Condolezza Rice"), 
		("Donald Rumsfeld", u"Donald Rumsfeld"), 
		("George Tenet", u"George Tenet"), 
		("George W. Casey, Jr", u"George W. Casey, Jr"), 
		("John Ashcroft", u"John Ashcroft"), 
		("John Negroponte", u"John Negroponte"), 
		("John Snow", u"John Snow"), 
		("Paul Bremer", u"Paul Bremer"), 
		("Ricardo Sanchez", u"Ricardo Sanchez"), 
		("Richard Myers", u"Richard Myers"), 
		("Spencer Abraham", u"Spencer Abraham"), 
		("Tom Ridge", u"Tom Ridge"), 
		("Tommy Franks", u"Tommy Franks"), 
		)
),
("1984", (
		("Director of Reform", u"Director of Reform"), 
		("Minister of Love", u"Minister of Love"), 
		("Minister of Peace", u"Minister of Peace"), 
		("Minister of Plenty", u"Minister of Plenty"), 
		("Minister of Truth", u"Minister of Truth"), 
		("President of Proletariat", u"President of Proletariat"), 
		("Proletariat Administrator", u"Proletariat Administrator"), 
		("Secretary of Armed Forces", u"Secretary of Armed Forces"), 
		("Secretary of Culture", u"Secretary of Culture"), 
		("Secretary of Economy", u"Secretary of Economy"), 
		("Secretary of Education", u"Secretary of Education"), 
		("Secretary of Foreign Intelligence", u"Secretary of Foreign Intelligence"), 
		)
),
("AD HOC", (
		("Confidential #1", u"Confidential #1"), 
		("Confidential #2", u"Confidential #2"), 
		("Confidential #3", u"Confidential #3"), 
		("Confidential #4", u"Confidential #4"), 
		("Confidential #5", u"Confidential #5"), 
		("Confidential #6", u"Confidential #6"), 
		("Confidential #7", u"Confidential #7"), 
		("Confidential #8", u"Confidential #8"), 
		("Confidential #9", u"Confidential #9"),	
		("Confidential #10", u"Confidential #10"), 
		("Confidential #11", u"Confidential #11"), 
		("Confidential #12", u"Confidential #12"), 
		("Confidential #13", u"Confidential #13"), 
		("Confidential #14", u"Confidential #14"), 
		("Confidential #15", u"Confidential #15"),
		)
),
("UNSC", (
		("Armenia", u"Armenia"), 
		("Belgium", u"Belgium"), 
		("Brazil", u"Brazil"), 
		("Canada", u"Canada"), 
		("China", u"China"), 
		("Ethiopia", u"Ethiopia"), 
		("France", u"France"), 
		("Morocco", u"Morocco"), 
		("Pakistan", u"Pakistan"), 
		("Russia", u"Russia"), 
		("Saudi Arabia", u"Saudi Arabia"), 
		("USA", u"USA"), 
		("Uganda", u"Uganda"), 
		("United Kingdom", u"United Kingdom"), 
		("Venezuela", u"Venezuela"), 
		)
),
("Mughal", (
		("Darogha-I Dak Wa Sawanih (Chief of Intelligence and Police)", u"Darogha-I Dak Wa Sawanih (Chief of Intelligence and Police)"), 
		("Duke of Goa", u"Duke of Goa"), 
		("Emissary of House Dinajara", u"Emissary of House Dinajara"), 
		("Lord of Rajasthan", u"Lord of Rajasthan"), 
		("Lord of Rajasthan", u"Lord of Rajasthan"), 
		("Marathan Ambassador", u"Marathan Ambassador"), 
		("Mir Bakhshi (Minister of War)", u"Mir Bakhshi (Minister of War)"), 
		("Muhtasib (Officer of Religious Morals)", u"Muhtasib (Officer of Religious Morals)"), 
		("Sadr(Chief Justice)", u"Sadr(Chief Justice)"), 
		("Sipah Salar(Governor of Bijapur)", u"Sipah Salar(Governor of Bijapur)"), 
		("Sipah Salar(Governor of Gujarat)", u"Sipah Salar(Governor of Gujarat)"), 
		("Sipah Salar(Governor of Hyderabad)", u"Sipah Salar(Governor of Hyderabad)"), 
		("Sipah Salar(Governor of Punjab)", u"Sipah Salar(Governor of Punjab)"), 
		("Sipah Salar(Governor of Rajput)", u"Sipah Salar(Governor of Rajput)"), 
		("Vizier (Minister of Finance)", u"Vizier (Minister of Finance)"), 
		("Vizier (Minister of Foreign Affairs)", u"Vizier (Minister of Foreign Affairs)"), 
		)
),
)

ASSIGN_TYPE = (( True, 'Country'), (False, 'Character'))

COUNTRYLIST = [
	"Afghanistan",
	"Albania",
	"Algeria",
	"Andorra",
	"Angola",
	"Antigua and Barbuda",
	"Argentina",
	"Armenia",
	"Australia",
	"Austria",
	"Azerbaijan",
	"Bahamas",
	"Bahrain",
	"Bangladesh",
	"Barbados",
	"Belarus",
	"Belgium",
	"Belize",
	"Benin",
	"Bhutan",
	"Bolivia",
	"Bosnia and Herzegovina",
	"Botswana",
	"Brazil",
	"Brunei",
	"Bulgaria",
	"Burkina Faso",
	"Burundi",
	"Cambodia",
	"Cameroon",
	"Canada",
	"Cape Verde",
	"Central African Republic",
	"Chad",
	"Chile",
	"China",
	"Colombia",
	"Comoros",
	"Congo",
	"Costa Rica",
	"Cote d'Ivoire",
	"Croatia",
	"Cuba",
	"Cyprus",
	"Czech Republic",
	"Democratic People's Republic of Korea",
	"Democratic Republic of Congo",
	"Denmark",
	"Dijibouti",
	"Dominican Republic",
	"Ecuador",
	"Egypt",
	"El Salvador",
	"Equitorial Guinea",
	"Eritrea",
	"Estonia",
	"Ethiopia",
	"Fiji",
	"Finland",
	"France",
	"Gabon",
	"Gambia",
	"Georgia",
	"Germany",
	"Ghana",
	"Greece",
	"Grenada",
	"Guatemala",
	"Guinea",
	"Guinea - Bissau",
	"Guyana",
	"Haiti",
	"Honduras",
	"Hungary",
	"Iceland",
	"India",
	"Indonesia",
	"Iran",
	"Iraq",
	"Ireland",
	"Israel",
	"Italy",
	"Jamaica",
	"Japan",
	"Jordan",
	"Kazakhstan",
	"Kenya",
	"Kuwait",
	"Kyrgyzstan",
	"Lao People's Democratic Republic",
	"Latvia",
	"Lebanon",
	"Lesotho",
	"Liberia",
	"Libya",
	"Liechtenstein",
	"Lithuania",
	"Luxembourg",
	"Madagascar",
	"Malawi",
	"Malaysia",
	"Maldives",
	"Mali",
	"Malta",
	"Marshall Islands",
	"Mauritania",
	"Mauritius",
	"Mexico",
	"Federated States of Micronesia",
	"Monaco",
	"Mongolia",
	"Montenegro",
	"Morocco",
	"Mozambique",
	"Myanmar",
	"Namibia",
	"Nauru",
	"Nepal",
	"Netherlands",
	"New Zealand",
	"Nicaragua",
	"Niger",
	"Nigeria",
	"Norway",
	"Oman",
	"Pakistan",
	"Palau",
	"Panama",
	"Papa New Guinea",
	"Paraguay",
	"Peru",
	"Philippines",
	"Poland",
	"Portugal",
	"Qatar",
	"Republic of Korea",
	"Republic of Moldova",
	"Romania",
	"Russian Federation",
	"Rwanda",
	"Saint Kitts and Nevis",
	"Saint Lucia",
	"Saint Vincent and the Grenadines",
	"Samoa",
	"San Marino",
	"Saudi Arabia",
	"Senegal",
	"Serbia",
	"Seychelles",
	"Sierra Leone",
	"Singapore",
	"Slovakia",
	"Slovenia",
	"Solomon Islands",
	"Somalia",
	"South Africa",
	"South Sudan",
	"Spain",
	"Sri Lanka",
	"Sudan",
	"Surimane",
	"Swaziland",
	"Sweden",
	"Switzerland",
	"Syrian Arab Republic",
	"Tajikistan",
	"Thailand",
	"Republic of Macedonia",
	"Timor-Leste",
	"Togo",
	"Tonga",
	"Trinidad and Tobago",
	"Tunisia",
	"Turkey",
	"Turkmenistan",
	"Tulavu",
	"Uganda",
	"Ukraine",
	"United Arab Emirates",
	"United Kingdom",
	"United Republic of Tanzania",
	"United States of America",
	"Uruguay",
	"Uzbekistan",
	"Vanuatu",
	"Venezuela",
	"Viet Nam",
	"Yemen",
	"Zambia",
	"Zimbabwe",	
]

