# -*- coding: utf-8 -*-

DELEGATION_FEE = 90

MAX_NUM_DELEGATES = 100

MIN_NUM_DELEGATES = 0

COUNTRIESFULL = (('AF', u'Afghanistan'), ('AX', u'\xc5land Islands'), ('AL', u'Albania'), ('DZ', u'Algeria'), ('AS', u'American Samoa'), ('AD', u'Andorra'), ('AO', u'Angola'), ('AI', u'Anguilla'), ('AQ', u'Antarctica'), ('AG', u'Antigua and Barbuda'), ('AR', u'Argentina'), ('AM', u'Armenia'), ('AW', u'Aruba'), ('SH', u'Ascension and Tristan Da Cunha Saint Helena'), ('AU', u'Australia'), ('AT', u'Austria'), ('AZ', u'Azerbaijan'), ('BS', u'Bahamas'), ('BH', u'Bahrain'), ('BD', u'Bangladesh'), ('BB', u'Barbados'), ('BY', u'Belarus'), ('BE', u'Belgium'), ('BZ', u'Belize'), ('BJ', u'Benin'), ('BM', u'Bermuda'), ('BT', u'Bhutan'), ('VE', u'Bolivarian Republic of Venezuela'), ('BO', u'Bolivia, Plurinational State of'), ('BQ', u'Bonaire, Sint Eustatius and Saba'), ('BA', u'Bosnia and Herzegovina'), ('BW', u'Botswana'), ('BV', u'Bouvet Island'), ('BR', u'Brazil'), ('IO', u'British Indian Ocean Territory'), ('VG', u'British Virgin Islands'), ('BN', u'Brunei Darussalam'), ('BG', u'Bulgaria'), ('BF', u'Burkina Faso'), ('BI', u'Burundi'), ('KH', u'Cambodia'), ('CM', u'Cameroon'), ('CA', u'Canada'), ('CV', u'Cape Verde'), ('KY', u'Cayman Islands'), ('CF', u'Central African Republic'), ('TD', u'Chad'), ('CL', u'Chile'), ('CN', u'China'), ('CX', u'Christmas Island'), ('CC', u'Cocos (Keeling) Islands'), ('CO', u'Colombia'), ('KM', u'Comoros'), ('CG', u'Congo'), ('CD', u'Congo, The Democratic Republic of the'), ('CK', u'Cook Islands'), ('CR', u'Costa Rica'), ('CI', u"C\xf4te D'ivoire"), ('HR', u'Croatia'), ('CU', u'Cuba'), ('CW', u'Cura\xe7ao'), ('CY', u'Cyprus'), ('CZ', u'Czech Republic'), ('KP', u"Democratic People's Republic of Korea"), ('DK', u'Denmark'), ('DJ', u'Djibouti'), ('DM', u'Dominica'), ('DO', u'Dominican Republic'), ('EC', u'Ecuador'), ('EG', u'Egypt'), ('SV', u'El Salvador'), ('GQ', u'Equatorial Guinea'), ('ER', u'Eritrea'), ('EE', u'Estonia'), ('ET', u'Ethiopia'), ('FK', u'Falkland Islands (Malvinas)'), ('FO', u'Faroe Islands'), ('FM', u'Federated States of Micronesia'), ('FJ', u'Fiji'), ('FI', u'Finland'), ('FR', u'France'), ('GF', u'French Guiana'), ('PF', u'French Polynesia'), ('TF', u'French Southern Territories'), ('GA', u'Gabon'), ('GM', u'Gambia'), ('GE', u'Georgia'), ('DE', u'Germany'), ('GH', u'Ghana'), ('GI', u'Gibraltar'), ('GR', u'Greece'), ('GL', u'Greenland'), ('GD', u'Grenada'), ('GP', u'Guadeloupe'), ('GU', u'Guam'), ('GT', u'Guatemala'), ('GG', u'Guernsey'), ('GN', u'Guinea'), ('GW', u'Guinea-bissau'), ('GY', u'Guyana'), ('HT', u'Haiti'), ('HM', u'Heard Island and McDonald Islands'), ('VA', u'Holy See (Vatican City State)'), ('HN', u'Honduras'), ('HK', u'Hong Kong'), ('HU', u'Hungary'), ('IS', u'Iceland'), ('IN', u'India'), ('ID', u'Indonesia'), ('IR', u'Iran, Islamic Republic of'), ('IQ', u'Iraq'), ('IE', u'Ireland'), ('IR', u'Islamic Republic of Iran'), ('IM', u'Isle of Man'), ('IL', u'Israel'), ('IT', u'Italy'), ('JM', u'Jamaica'), ('JP', u'Japan'), ('JE', u'Jersey'), ('JO', u'Jordan'), ('KZ', u'Kazakhstan'), ('KE', u'Kenya'), ('KI', u'Kiribati'), ('KP', u"Korea, Democratic People's Republic of"), ('KR', u'Korea, Republic of'), ('KW', u'Kuwait'), ('KG', u'Kyrgyzstan'), ('LA', u"Lao People's Democratic Republic"), ('LV', u'Latvia'), ('LB', u'Lebanon'), ('LS', u'Lesotho'), ('LR', u'Liberia'), ('LY', u'Libya'), ('LI', u'Liechtenstein'), ('LT', u'Lithuania'), ('LU', u'Luxembourg'), ('MO', u'Macao'), ('MK', u'Macedonia, The Former Yugoslav Republic of'), ('MG', u'Madagascar'), ('MW', u'Malawi'), ('MY', u'Malaysia'), ('MV', u'Maldives'), ('ML', u'Mali'), ('MT', u'Malta'), ('MH', u'Marshall Islands'), ('MQ', u'Martinique'), ('MR', u'Mauritania'), ('MU', u'Mauritius'), ('YT', u'Mayotte'), ('MX', u'Mexico'), ('FM', u'Micronesia, Federated States of'), ('MD', u'Moldova, Republic of'), ('MC', u'Monaco'), ('MN', u'Mongolia'), ('ME', u'Montenegro'), ('MS', u'Montserrat'), ('MA', u'Morocco'), ('MZ', u'Mozambique'), ('MM', u'Myanmar'), ('NA', u'Namibia'), ('NR', u'Nauru'), ('NP', u'Nepal'), ('NL', u'Netherlands'), ('NC', u'New Caledonia'), ('NZ', u'New Zealand'), ('NI', u'Nicaragua'), ('NE', u'Niger'), ('NG', u'Nigeria'), ('NU', u'Niue'), ('NF', u'Norfolk Island'), ('MP', u'Northern Mariana Islands'), ('NO', u'Norway'), ('PS', u'Occupied Palestinian Territory'), ('OM', u'Oman'), ('PK', u'Pakistan'), ('PW', u'Palau'), ('PS', u'Palestinian Territory, Occupied'), ('PA', u'Panama'), ('PG', u'Papua New Guinea'), ('PY', u'Paraguay'), ('PE', u'Peru'), ('PH', u'Philippines'), ('PN', u'Pitcairn'), ('BO', u'Plurinational State of Bolivia'), ('PL', u'Poland'), ('PT', u'Portugal'), ('TW', u'Province of China Taiwan'), ('PR', u'Puerto Rico'), ('QA', u'Qatar'), ('KR', u'Republic of Korea'), ('MD', u'Republic of Moldova'), ('RE', u'R\xe9union'), ('RO', u'Romania'), ('RU', u'Russian Federation'), ('RW', u'Rwanda'), ('BL', u'Saint Barth\xe9lemy'), ('SH', u'Saint Helena, Ascension and Tristan Da Cunha'), ('KN', u'Saint Kitts and Nevis'), ('LC', u'Saint Lucia'), ('MF', u'Saint Martin (French Part)'), ('PM', u'Saint Pierre and Miquelon'), ('VC', u'Saint Vincent and the Grenadines'), ('WS', u'Samoa'), ('SM', u'San Marino'), ('ST', u'Sao Tome and Principe'), ('SA', u'Saudi Arabia'), ('SN', u'Senegal'), ('RS', u'Serbia'), ('SC', u'Seychelles'), ('SL', u'Sierra Leone'), ('SG', u'Singapore'), ('BQ', u'Sint Eustatius and Saba Bonaire'), ('SX', u'Sint Maarten (Dutch Part)'), ('SK', u'Slovakia'), ('SI', u'Slovenia'), ('SB', u'Solomon Islands'), ('SO', u'Somalia'), ('ZA', u'South Africa'), ('GS', u'South Georgia and the South Sandwich Islands'), ('SS', u'South Sudan'), ('ES', u'Spain'), ('LK', u'Sri Lanka'), ('SD', u'Sudan'), ('SR', u'Suriname'), ('SJ', u'Svalbard and Jan Mayen'), ('SZ', u'Swaziland'), ('SE', u'Sweden'), ('CH', u'Switzerland'), ('SY', u'Syrian Arab Republic'), ('TW', u'Taiwan, Province of China'), ('TJ', u'Tajikistan'), ('TZ', u'Tanzania, United Republic of'), ('TH', u'Thailand'), ('CD', u'The Democratic Republic of the Congo'), ('MK', u'The Former Yugoslav Republic of Macedonia'), ('TL', u'Timor-leste'), ('TG', u'Togo'), ('TK', u'Tokelau'), ('TO', u'Tonga'), ('TT', u'Trinidad and Tobago'), ('TN', u'Tunisia'), ('TR', u'Turkey'), ('TM', u'Turkmenistan'), ('TC', u'Turks and Caicos Islands'), ('TV', u'Tuvalu'), ('VI', u'U.S. Virgin Islands'), ('UG', u'Uganda'), ('UA', u'Ukraine'), ('AE', u'United Arab Emirates'), ('GB', u'United Kingdom'), ('TZ', u'United Republic of Tanzania'), ('US', u'United States'), ('UM', u'United States Minor Outlying Islands'), ('UY', u'Uruguay'), ('UZ', u'Uzbekistan'), ('VU', u'Vanuatu'), ('VE', u'Venezuela, Bolivarian Republic of'), ('VN', u'Viet Nam'), ('VG', u'Virgin Islands, British'), ('VI', u'Virgin Islands, U.S.'), ('WF', u'Wallis and Futuna'), ('EH', u'Western Sahara'), ('YE', u'Yemen'), ('ZM', u'Zambia'), ('ZW', u'Zimbabwe'))

COUNTRIES = (
	('AF', u'Afghanistan'), ('AL', u'Albania'), ('AC', u'ALECSO'),('DZ', u'Algeria'), 
	('AD', u'Andorra'), ('AO', u'Angola'), 
	('AG', u'Antigua and Barbuda'), ('AR', u'Argentina'), ('AM', u'Armenia'), 
	('AU', u'Australia'), 
	('AT', u'Austria'), ('AZ', u'Azerbaijan'), ('BS', u'Bahamas'), 
	('BH', u'Bahrain'), ('BD', u'Bangladesh'), ('BB', u'Barbados'), 
	('BY', u'Belarus'), ('BE', u'Belgium'), ('BZ', u'Belize'), 
	('BJ', u'Benin'), ('BT', u'Bhutan'), 
	('BO', u'Bolivia, Plurinational State of'), 
	('BA', u'Bosnia and Herzegovina'), ('BW', u'Botswana'), 
	('BR', u'Brazil'), ('BN', u'Brunei Darussalam'), ('BG', u'Bulgaria'), 
	('BF', u'Burkina Faso'), ('BI', u'Burundi'), ('KH', u'Cambodia'), 
	('CM', u'Cameroon'), ('CA', u'Canada'), ('CV', u'Cape Verde'), 
	('TD', u'Chad'), 
	('CL', u'Chile'), ('CN', u'China'), ('CO', u'Colombia'), ('KM', u'Comoros'), 
	('CG', u'Congo'), ('CR', u'Costa Rica'), ('CI', u"C\xf4te D'ivoire"), ('HR', u'Croatia'), 
	('CU', u'Cuba'), ('CY', u'Cyprus'), 
	('CZ', u'Czech Republic'), ('KP', u"Democratic People's Republic of Korea"),
	('RC', u'Democratic Republic of Congo'), ('DK', u'Denmark'), 
	('DJ', u'Djibouti'), ('DO', u'Dominican Republic'), 
	('EC', u'Ecuador'), ('EG', u'Egypt'), ('SV', u'El Salvador'), 
	('GQ', u'Equatorial Guinea'), ('ER', u'Eritrea'),
	('ET', u'Ethiopia'), ('FJ', u'Fiji'), ('FI', u'Finland'), 
	('FR', u'France'), ('GA', u'Gabon'), ('GM', u'Gambia'), 
	('GE', u'Georgia'), ('DE', u'Germany'), ('GH', u'Ghana'), 
	('GR', u'Greece'), ('GD', u'Grenada'), ('GT', u'Guatemala'), 
	('GN', u'Guinea'), ('GY', u'Guyana'), ('HT', u'Haiti'), 
	('HN', u'Honduras'), ('HU', u'Hungary'), 
	('IS', u'Iceland'), ('IN', u'India'), ('ID', u'Indonesia'),
	('IM', u'International Organization for Migration'),
	('IR', u'Iran, Islamic Republic of'), ('IQ', u'Iraq'), ('IE', u'Ireland'), 
	('IL', u'Israel'), ('IT', u'Italy'), ('JM', u'Jamaica'), ('JP', u'Japan'), 
	('JO', u'Jordan'), ('KZ', u'Kazakhstan'), ('KE', u'Kenya'), 
	('KW', u'Kuwait'), ('KG', u'Kyrgyzstan'), 
	('LA', u"Lao People's Democratic Republic"), ('LB', u'Lebanon'), 
	('LS', u'Lesotho'), ('LR', u'Liberia'), ('LY', u'Libya'), 
	('LT', u'Lithuania'), ('LU', u'Luxembourg'), 
	('MG', u'Madagascar'), 
	('MW', u'Malawi'), ('MY', u'Malaysia'), ('MV', u'Maldives'), 
	('ML', u'Mali'), ('MT', u'Malta'), ('MR', u'Mauritania'), 
	('MU', u'Mauritius'), ('MX', u'Mexico'), ('MC', u'Monaco'), 
	('MN', u'Mongolia'), ('MA', u'Morocco'), ('MZ', u'Mozambique'), 
	('MM', u'Myanmar'), ('NA', u'Namibia'),
	('NP', u'Nepal'), ('NL', u'Netherlands'),
	('NZ', u'New Zealand'), ('NI', u'Nicaragua'), ('NE', u'Niger'), 
	('NG', u'Nigeria'), ('NO', u'Norway'), 
	('OM', u'Oman'), ('IC', u'Organization of the Islamic Cooperation'), ('PK', u'Pakistan'), 
	('PS', u'Palestine'), ('PA', u'Panama'), 
	('PG', u'Papua New Guinea'), ('PY', u'Paraguay'), ('PE', u'Peru'), ('PH', u'Philippines'), 
	('PL', u'Poland'), ('PT', u'Portugal'), ('QA', u'Qatar'), 
	('KR', u'Republic of Korea'), ('MD', u'Republic of Macedonia'), 
	('RO', u'Romania'), ('RU', u'Russian Federation'), 
	('RW', u'Rwanda'), ('SR', u'Sahrawi Republic'), 
	('KN', u'Saint Kitts and Nevis'), ('LC', u'Saint Lucia'), 
	('VC', u'Saint Vincent and the Grenadines'), ('ST', u'Sao Tome and Principe'), 
	('SA', u'Saudi Arabia'), ('SN', u'Senegal'), 
	('RS', u'Serbia'), ('SC', u'Seychelles'), ('SL', u'Sierra Leone'), 
	('SG', u'Singapore'), ('SK', u'Slovakia'), ('SO', u'Somalia'), ('ZA', u'South Africa'), 
	('SS', u'South Sudan'), 
	('ES', u'Spain'), ('LK', u'Sri Lanka'), ('SD', u'Sudan'), ('SR', u'Suriname'), 
	('SZ', u'Swaziland'), ('SE', u'Sweden'), 
	('CH', u'Switzerland'), ('SY', u'Syrian Arab Republic'), ('TH', u'Thailand'), 
	('TL', u'Timor-leste'), ('TG', u'Togo'), 
	('TT', u'Trinidad and Tobago'), 
	('TN', u'Tunisia'), ('TR', u'Turkey'), ('TM', u'Turkmenistan'), 
	('UG', u'Uganda'), ('UA', u'Ukraine'), ('UN', u'UNHCR'), ('AE', u'United Arab Emirates'), 
	('GB', u'United Kingdom'), ('TZ', u'United Republic of Tanzania'), 
	('US', u'United States of America'), ('UY', u'Uruguay'), ('UZ', u'Uzbekistan'), 
	('VU', u'Vanuatu'), 
	('VE', u'Venezuela, Bolivarian Republic of'), ('VN', u'Viet Nam'), 
	('YE', u'Yemen'), 
	('ZM', u'Zambia'), ('ZW', u'Zimbabwe'))


COUNTRIESNGO = (
	("Afghanistan", u"Afghanistan"),
	("AFL-CIO, USA", u"AFL-CIO, USA"),
	("Albania", u"Albania"),
	("ALECSO", u"ALECSO"),
	("Algeria", u"Algeria"),
	("All India Organisation of Employers ", u"All India Organisation of Employers "),
	("All-China Federation of Trade Unions", u"All-China Federation of Trade Unions"),
	("All-Russian Confederation of Labour", u"All-Russian Confederation of Labour"),
	("Amnesty International", u"Amnesty International"),
	("Andorra", u"Andorra"),
	("Angola", u"Angola"),
	("Antigua and Barbuda", u"Antigua and Barbuda"),
	("Argentina", u"Argentina"),
	("Armenia", u"Armenia"),
	("Aruba", u"Aruba"),
	("Asociacion Nacional de Empresarios de Colombia", u"Asociacion Nacional de Empresarios de Colombia"),
	("Australia", u"Australia"),
	("Austria", u"Austria"),
	("Azerbaijan", u"Azerbaijan"),
	("Bahamas", u"Bahamas"),
	("Bahrain", u"Bahrain"),
	("Bangladesh", u"Bangladesh"),
	("Bangladesh Employers' Federation", u"Bangladesh Employers' Federation"),
	("Bangladesh Free Trade Union Congress", u"Bangladesh Free Trade Union Congress"),
	("Barbados", u"Barbados"),
	("Belarus", u"Belarus"),
	("Belgium", u"Belgium"),
	("Belize", u"Belize"),
	("Benin", u"Benin"),
	("Bhutan", u"Bhutan"),
	("Bolivia", u"Bolivia"),
	("Bosnia and Herzegovina", u"Bosnia and Herzegovina"),
	("Botswana", u"Botswana"),
	("Botswana Confederation of Commerce, Industry, and Manpower", u"Botswana Confederation of Commerce, Industry, and Manpower"),
	("Botswana Federation of Trade Unions", u"Botswana Federation of Trade Unions"),
	("BP", u"BP"),
	("Brazil", u"Brazil"),
	("BRIDGE", u"BRIDGE"),
	("Brunei", u"Brunei"),
	("Bulgaria", u"Bulgaria"),
	("Burkina Faso", u"Burkina Faso"),
	("Burundi", u"Burundi"),
	("Business Unity South Africa", u"Business Unity South Africa"),
	("Camara de Industrias de Guayaquil", u"Camara de Industrias de Guayaquil"),
	("Cambodia", u"Cambodia"),
	("Cameroon", u"Cameroon"),
	("Canada", u"Canada"),
	("Canadian Employers' Council", u"Canadian Employers' Council"),
	("Canadian labour Congress", u"Canadian labour Congress"),
	("Cape Verde", u"Cape Verde"),
	("CDC", u"CDC"),
	("Central African Republic", u"Central African Republic"),
	("Central Organisation of Free Trade Unions, Uganda (COFTU)", u"Central Organisation of Free Trade Unions, Uganda (COFTU)"),
	("Central Organization of Trade Unions (Kenya)", u"Central Organization of Trade Unions (Kenya)"),
	("Central Union of Workers, Colombia", u"Central Union of Workers, Colombia"),
	("Centre of Indian Trade Unions", u"Centre of Indian Trade Unions"),
	("Chad", u"Chad"),
	("Chevron", u"Chevron"),
	("Chile", u"Chile"),
	("China", u"China"),
	("China Enterprise Confederation", u"China Enterprise Confederation"),
	("Chinese Taipei Federation of Industries", u"Chinese Taipei Federation of Industries"),
	("Colombia", u"Colombia"),
	("Comoros", u"Comoros"),
	("Confederacao Nacional da Industria", u"Confederacao Nacional da Industria"),
	("Confederacion de la Produccion y del Comercio", u"Confederacion de la Produccion y del Comercio"),
	("Confederacion Patronal de la Republica Mexicana ", u"Confederacion Patronal de la Republica Mexicana "),
	("Confederation of British Industry", u"Confederation of British Industry"),
	("Confederation of German Employers", u"Confederation of German Employers"),
	("Confederation of Indonesia Prosperous Trade Union", u"Confederation of Indonesia Prosperous Trade Union"),
	("Confederation of Netherlands Industry and Employers", u"Confederation of Netherlands Industry and Employers"),
	("Confederation of Public Workers' Unions (Turkey)", u"Confederation of Public Workers' Unions (Turkey)"),
	("Confederation of Workers of Venezuela", u"Confederation of Workers of Venezuela"),
	("Congo", u"Congo"),
	("Congress of South African Trade Unions", u"Congress of South African Trade Unions"),
	("Conseil national du Patronat Burkinabé", u"Conseil national du Patronat Burkinabé"),
	("Consejo Superior de la Empresa Privada", u"Consejo Superior de la Empresa Privada"),
	("Costa Rica", u"Costa Rica"),
	("Côte d'Ivoire", u"Côte d'Ivoire"),
	("Council of Saudi Chambers", u"Council of Saudi Chambers"),
	("Croatia", u"Croatia"),
	("Cuba", u"Cuba"),
	("Curacao", u"Curacao"),
	("Cyprus", u"Cyprus"),
	("Czech Republic", u"Czech Republic"),
	("Democratic People's Republic of Korea", u"Democratic People's Republic of Korea"),
	("Democratic Republic of Congo", u"Democratic Republic of Congo"),
	("Denmark", u"Denmark"),
	("Dijibouti", u"Dijibouti"),
	("Dominican Republic", u"Dominican Republic"),
	("Ecuador", u"Ecuador"),
	("Ecuador Confederation of Free Trade Union Organizations", u"Ecuador Confederation of Free Trade Union Organizations"),
	("EFSA", u"EFSA"),
	("Egypt", u"Egypt"),
	("Egyptian Trade Union Federation", u"Egyptian Trade Union Federation"),
	("El Salvador", u"El Salvador"),
	("EMEA", u"EMEA"),
	("Employers' Federation of Ceylon (Sri Lanka)", u"Employers' Federation of Ceylon (Sri Lanka)"),
	("Employers' Federation of Pakistan", u"Employers' Federation of Pakistan"),
	("Employers' Organizations", u"Employers' Organizations"),
	("ENVI", u"ENVI"),
	("Equitorial Guinea", u"Equitorial Guinea"),
	("Eritrea", u"Eritrea"),
	("Estonia", u"Estonia"),
	("Ethiopia", u"Ethiopia"),
	("European Medicines Agency", u"European Medicines Agency"),
	("ExxonMobil", u"ExxonMobil"),
	("Federacion de camaras y Asociaciones de Comercio y Produccion de Venezuela", u"Federacion de camaras y Asociaciones de Comercio y Produccion de Venezuela"),
	("Federated States of Micronesia", u"Federated States of Micronesia"),
	("Federation des Entreprises du Congo", u"Federation des Entreprises du Congo"),
	("Federation Dutch Labour Movement", u"Federation Dutch Labour Movement"),
	("Federation of American Women's Clubs Overseas", u"Federation of American Women's Clubs Overseas"),
	("Federation of Egyptian Industries", u"Federation of Egyptian Industries"),
	("Federation of Kenya Employers", u"Federation of Kenya Employers"),
	("Federation of Korean Trade Unions", u"Federation of Korean Trade Unions"),
	("Federation of Oil Unions in Iraq", u"Federation of Oil Unions in Iraq"),
	("Federation of Trade Unions of the Republic of Kazakhstan", u"Federation of Trade Unions of the Republic of Kazakhstan"),
	("Federation of Uganda Employers", u"Federation of Uganda Employers"),
	("Fiji", u"Fiji"),
	("Finland", u"Finland"),
	("France", u"France"),
	("French Democratic Confederation of Labour", u"French Democratic Confederation of Labour"),
	("Gabon", u"Gabon"),
	("Gambia", u"Gambia"),
	("General Confederation of Peruvian Workers (CGTP)", u"General Confederation of Peruvian Workers (CGTP)"),
	("General Federation of Jordanian Trade Unions", u"General Federation of Jordanian Trade Unions"),
	("General Federation of Trade Unions (Syria)", u"General Federation of Trade Unions (Syria)"),
	("General Federation of Trade Unions (UK)", u"General Federation of Trade Unions (UK)"),
	("Georgia", u"Georgia"),
	("German Christian Workers' Federation", u"German Christian Workers' Federation"),
	("Germany", u"Germany"),
	("Ghana", u"Ghana"),
	("Ghana Employers' Association", u"Ghana Employers' Association"),
	("Greece", u"Greece"),
	("Greenpeace", u"Greenpeace"),
	("Grenada", u"Grenada"),
	("Guam", u"Guam"),
	("Guatemala", u"Guatemala"),
	("Guinea", u"Guinea"),
	("Guinea - Bissau", u"Guinea - Bissau"),
	("Guyana", u"Guyana"),
	("Haiti", u"Haiti"),
	("Honduras", u"Honduras"),
	("Hong Kong, China", u"Hong Kong, China"),
	("Hungary", u"Hungary"),
	("Husky", u"Husky"),
	("Iceland", u"Iceland"),
	("Imperial", u"Imperial"),
	("India", u"India"),
	("Indonesia", u"Indonesia"),
	("International Federation of Red Cross and Red Crescent Societies", u"International Federation of Red Cross and Red Crescent Societies"),
	("International Service for Human Rights", u"International Service for Human Rights"),
	("Iran", u"Iran"),
	("Iranian Confederation of Employers' Associations", u"Iranian Confederation of Employers' Associations"),
	("Iraq", u"Iraq"),
	("Ireland", u"Ireland"),
	("Israel", u"Israel"),
	("Italian Confederation of Workers' Trade Union", u"Italian Confederation of Workers' Trade Union"),
	("Italy", u"Italy"),
	("Jamaica", u"Jamaica"),
	("Japan", u"Japan"),
	("Japan Business Federation", u"Japan Business Federation"),
	("Jordan", u"Jordan"),
	("Kazakhstan", u"Kazakhstan"),
	("Kenya", u"Kenya"),
	("Kuwait", u"Kuwait"),
	("Kyrgyzstan", u"Kyrgyzstan"),
	("Lao People's Democratic Republic", u"Lao People's Democratic Republic"),
	("Latvia", u"Latvia"),
	("Lebanon", u"Lebanon"),
	("Lesotho", u"Lesotho"),
	("Liberia", u"Liberia"),
	("Libya", u"Libya"),
	("Liechtenstein", u"Liechtenstein"),
	("Lithuania", u"Lithuania"),
	("Luxembourg", u"Luxembourg"),
	("Macao, China", u"Macao, China"),
	("Madagascar", u"Madagascar"),
	("Malawi", u"Malawi"),
	("Malaysia", u"Malaysia"),
	("Maldives", u"Maldives"),
	("Mali", u"Mali"),
	("Malta", u"Malta"),
	("Marshall Islands", u"Marshall Islands"),
	("Mauritania", u"Mauritania"),
	("Mauritius", u"Mauritius"),
	("Mexico", u"Mexico"),
	("Monaco", u"Monaco"),
	("Mongolia", u"Mongolia"),
	("Montenegro", u"Montenegro"),
	("Morocco", u"Morocco"),
	("Mouvement des Entreprises de France", u"Mouvement des Entreprises de France"),
	("Mozambique", u"Mozambique"),
	("Myanmar", u"Myanmar"),
	("Namibia", u"Namibia"),
	("National Confederation of Workers of Burkina", u"National Confederation of Workers of Burkina"),
	("National Trade Unions' Federation (Libya)", u"National Trade Unions' Federation (Libya)"),
	("National Union of Congolese Workers", u"National Union of Congolese Workers"),
	("National Union of General Workers (Japan)", u"National Union of General Workers (Japan)"),
	("National Union of Mine and Metal Workers of the Mexican Republic", u"National Union of Mine and Metal Workers of the Mexican Republic"),
	("National Union of Workers (Sri Lanka)", u"National Union of Workers (Sri Lanka)"),
	("Nauru", u"Nauru"),
	("Nepal", u"Nepal"),
	("Netherlands", u"Netherlands"),
	("New Caledonia ", u"New Caledonia "),
	("New Zealand", u"New Zealand"),
	("Nicaragua", u"Nicaragua"),
	("Nicaraguan Workers' Centre", u"Nicaraguan Workers' Centre"),
	("Niger", u"Niger"),
	("Nigeria", u"Nigeria"),
	("Nigeria Employers' Consultative Association", u"Nigeria Employers' Consultative Association"),
	("Northern Mariana Islands", u"Northern Mariana Islands"),
	("Norway", u"Norway"),
	("Oman", u"Oman"),
	("Pakistan", u"Pakistan"),
	("Pakistan Workers Confederation", u"Pakistan Workers Confederation"),
	("Palau", u"Palau"),
	("Palestine", u"Palestine"),
	("Panama", u"Panama"),
	("Papa New Guinea", u"Papa New Guinea"),
	("Paraguay", u"Paraguay"),
	("Partners in Population Development", u"Partners in Population Development"),
	("PEPFAR", u"PEPFAR"),
	("Peru", u"Peru"),
	("Philippines", u"Philippines"),
	("Poland", u"Poland"),
	("Portugal", u"Portugal"),
	("Qatar", u"Qatar"),
	("Republic of Korea", u"Republic of Korea"),
	("Republic of Macedonia", u"Republic of Macedonia"),
	("Republic of Moldova", u"Republic of Moldova"),
	("Romania", u"Romania"),
	("Russian Federation", u"Russian Federation"),
	("Russian Union of Industrialists and Entrepreneurs ", u"Russian Union of Industrialists and Entrepreneurs "),
	("Rwanda", u"Rwanda"),
	("Saint Kitts and Nevis", u"Saint Kitts and Nevis"),
	("Saint Lucia", u"Saint Lucia"),
	("Saint Maarten", u"Saint Maarten"),
	("Saint Vincent and the Grenadines", u"Saint Vincent and the Grenadines"),
	("Samoa", u"Samoa"),
	("San Marino", u"San Marino"),
	("Saudi Arabia", u"Saudi Arabia"),
	("Senegal", u"Senegal"),
	("Serbia", u"Serbia"),
	("Seychelles", u"Seychelles"),
	("Shell", u"Shell"),
	("Sierra Leone", u"Sierra Leone"),
	("Sierra Leone Labour Congress", u"Sierra Leone Labour Congress"),
	("Singapore", u"Singapore"),
	("Slovakia", u"Slovakia"),
	("Slovenia", u"Slovenia"),
	("Solomon Islands", u"Solomon Islands"),
	("Somalia", u"Somalia"),
	("South Africa", u"South Africa"),
	("South Sudan", u"South Sudan"),
	("Spain", u"Spain"),
	("Sri Lanka", u"Sri Lanka"),
	("Sudan", u"Sudan"),
	("Surimane", u"Surimane"),
	("Swaziland", u"Swaziland"),
	("Sweden", u"Sweden"),
	("Swiss Federation of Trade Unions", u"Swiss Federation of Trade Unions"),
	("Switzerland", u"Switzerland"),
	("Syrian Arab Republic", u"Syrian Arab Republic"),
	("Taiwan Confederation of Trade Unions", u"Taiwan Confederation of Trade Unions"),
	("Tajikistan", u"Tajikistan"),
	("Talisman Energy", u"Talisman Energy"),
	("Thailand", u"Thailand"),
	("The Employers' Association of Indonesia", u"The Employers' Association of Indonesia"),
	("The Trades Union Congress of Ghana", u"The Trades Union Congress of Ghana"),
	("Timor-Leste", u"Timor-Leste"),
	("Togo", u"Togo"),
	("Tonga", u"Tonga"),
	("TOTAL", u"TOTAL"),
	("Trinidad and Tobago", u"Trinidad and Tobago"),
	("Tulavu", u"Tulavu"),
	("Tunisia", u"Tunisia"),
	("Turkey", u"Turkey"),
	("Turkish Confederation of Employer Associations", u"Turkish Confederation of Employer Associations"),
	("Turkmenistan", u"Turkmenistan"),
	("Uganda", u"Uganda"),
	("Ukraine", u"Ukraine"),
	("UN Body on Petroleum ", u"UN Body on Petroleum "),
	("Unified Workers' Central, Brazil", u"Unified Workers' Central, Brazil"),
	("Union of Workers in Industry, Garages, Construction Firms, Mines, and Printers (Rwanda)", u"Union of Workers in Industry, Garages, Construction Firms, Mines, and Printers (Rwanda)"),
	("Union Patronale Suisse", u"Union Patronale Suisse"),
	("United Arab Emirates", u"United Arab Emirates"),
	("United Kingdom", u"United Kingdom"),
	("United Republic of Tanzania", u"United Republic of Tanzania"),
	("United States Council for International Business", u"United States Council for International Business"),
	("United States of America", u"United States of America"),
	("Uruguay", u"Uruguay"),
	("Uzbekistan", u"Uzbekistan"),
	("Vanuatu", u"Vanuatu"),
	("Venezuela", u"Venezuela"),
	("Viet Nam", u"Viet Nam"),
	("VSO", u"VSO"),
	("WHO", u"WHO"),
	("Workers' Central Union of Cuba", u"Workers' Central Union of Cuba"),
	("Workers' House of the Islamic Republic of Iran", u"Workers' House of the Islamic Republic of Iran"),
	("Workers' United Centre of Chile", u"Workers' United Centre of Chile"),
	("World Trade Organization", u"World Trade Organization"),
	("Yemen", u"Yemen"),
	("Zambia", u"Zambia"),
	("Zimbabwe", u"Zimbabwe")
)


YESNO = (( True, 'Yes'), (False, 'No'))

HOWYOUHEAR = (('brochure', 'Brochure'), ('letter', 'Letter'), ('website', 'Website'), ('another_school', 'Other School'), ('other', 'Other'))


TRUEFALSE = (( True, 'True'), (False, 'False'))


